<?php

return [
	'page_title'          => 'Quickadmin builder',
	'quickadmin_for'      => 'QuickAdminPanel for',
	'logout'              => 'Logout',
	'menu_manager'        => 'Menu Management',
	'user_management'     => 'User Management',
	'back_to_adminpanels' => 'Go back to adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Add Menu Item',
		'crud_menu_item' => 'CRUD Menu Item',
		'non_crud_menu_item' => 'Non-CRUD Menu Item',
		'parent_menu_item' => 'Parent Menu Item',
	],

	'menu' => [
		'no_items'                    => 'No menu items found.',
		'download'                    => 'Download adminpanel (:price)',
		'download_vip'                => 'Download adminpanel',
		'view_files'                  => 'View Laravel files',
		'create_new_crud'             => 'Create CRUD menu item',
		'create_new_custom'           => 'Create non-CRUD menu item',
		'create_new_parent_menu_item' => 'Create Parent menu item',
		'drag_drop_info'              => 'You can change menu positions with drag-drop',
		'save_changes_warning'        => 'Changes will be saved when you click Save positions',
		'save_positions'              => 'Save positions',
		'title'                       => 'Title',
		'edit'                        => 'Edit',
		'clone'                       => 'Clone',
		'delete'                      => 'Delete',
		'used_as_relationship'        => 'Used as a relationship',
		'how_to_use'                  => 'How to use downloaded adminpanel',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    You have successfully purchased adminpanel. Now you can view files and download it unlimited times.
		</div>
		<p>1. Extract the archive and put it in the folder you want</p>
		<p>2. Prepare your .env file there with database connection and other settings</p>
		<p>3. Run "<i>composer install</i>" command</p>
		<p>4. Run "<i>php artisan migrate --seed</i>" command. Notice: seed is important, because it will create the first admin user for you.</p>
		
		<br />
		
		<p>And that\'s it, go to your domain and login:</p>
		<p>
		Email: admin@admin.com<br />
		Password: password
		</p>
		
		Have fun using your adminpanel!
		',
		'close'                       => 'Close',

		'payment' => [
			'name'        => 'One time payment',
			'description' => 'Download Full Laravel Project (:price)',
		],

		'edit_custom'           => 'Edit Custom controller',
		'edit_parent_menu_item' => 'Edit Parent menu item',
		'clone_custom'           => 'Clone Custom controller',
		'clone_parent_menu_item' => 'Clone Parent menu item',
		'parent_menu_item' => 'Parent menu item',
		'visual_title' => 'Visual title',
		'icon' => 'Icon',
		'link_to_icons' => 'See all available icons - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD Settings',
		'add_fields' => 'Add Fields',
		'fields_notice' => '<b>Notice:</b> you <strong>don\'t</strong> need to add <b>ID</b> and <b>Timestamps</b> fields - they are added automatically.',
		'save_crud' => 'Save CRUD',
		'parent_menu_item' => 'Parent menu item',
		'new_crud_title' => 'New CRUD Title',
		'new_visual_title' => 'New Visual Title',
		'crud_title' => 'CRUD Title',
		'visual_title' => 'Visual Title',
		'crud_title_helper' => 'You may enter only characters, number and spaces.',
		'crud_title_second_helper' => 'Used to create menu item, models, controllers, database migrations.
                <br/>Title examples: <b>Countries</b>, <b>Companies</b>, <b>Books</b> etc.',
		'visual_title_helper' => 'Visual title of the CRUD which will be displayed in Menu.',
		'cannot_change_title' => 'You cannot change CRUD name, only fields.',
		'generate_following' => 'We will generate the following:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Database table',
		'what_actions_to_generate' => 'What actions to generate?',
		'create' => 'Create',
		'edit' => 'Edit',
		'show' => 'Show',
		'delete' => 'Delete',
		'generate_api' => 'Generate API Controller for this CRUD',
		'api_generated' => 'API was generated for this CRUD',
		'crud_icon' => 'CRUD Icon',
		'main_settings' => 'Main settings',
		'field_type' => 'Field type',
		'field_key' => 'Field key',
		'belongs_to_relationship' => 'Key that will be used in as function name (exclude _id).',
		'field_label' => 'Field label',
		'validation' => 'Validation',
		'nullable' => 'Nullable',
		'in_list' => 'In list?',
		'in_create' => 'In create?',
		'in_edit' => 'In edit?',
		'additional_settings' => 'Additional settings',
		'ck_editor' => 'Use CKEDITOR?',
		'size_mb' => 'Max size in MB',
		'width_px' => 'Max width in PX',
		'height_px' => 'Max height in PX',
		'radio_values' => 'Radio values:<br/> To add a value - click \'Add new Value set\' button and enter the data.',
		'label' => 'Label',
		'value' => 'Value',
		'add_new_key_value' => 'Add new Key/Value set',
		'default_value' => 'Default value',
		'relationship_model' => 'Relationship model',
		'relationship_field' => 'Relationship field',
		'enum_values' => 'ENUM values (comma separated)',
		'save_changes' => 'Save changes',
		'notice_save_crud' => 'Press Save CRUD to save your edited/created fields.',
	],

	'buy_modal' => [
		'title' => 'Here\'s what you\'re gonna get',
		'description' => 'This is a screenshot of a folder you will download after payment. It\'s a full Laravel project for your :title - ready to use immediately!',
		'buy' => 'BUY AND DOWNLOAD NOW (:price)',
	],

	're-order_fields' => 'Re-order fields',
	'field_type' => 'Field Type',
	'database_column' => 'Database column',
	'visual_title' => 'Visual Title',
	'field_type_in_form' => 'Field type in form',
	'field_name_in_form_and_database' => 'Field name in form and database',
	'field_label_in_form_and_index_page' => 'Field label in form and index page',
	'edit' => 'Edit',
	'remove_field_from_crud' => 'Remove field from CRUD',
	'remove' => 'Remove',
	'add_field' => 'Add field',
	'you_need_at_least_one_field' => 'You need at least one field',

	'mb' => 'MB',
	'(w)_px' => '(w) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'Save CRUD',
	'add_new_crud' => 'Add new CRUD',
	'download_full_laravel_project_999' => 'Download Full Laravel Project ($9.99)',
	'download_files' => 'Download files',
	'view_files_free' => 'View Files (FREE)',
	'cruds' => 'CRUDs',
	'title' => 'Title',
	'created_at' => 'Created at',
	'updated_at' => 'Updated at',
	'clone' => 'Clone',
	'no_cruds_created_yet' => 'No CRUDs created yet.',
	'one_time_payment' => 'One time payment',
	'file_viewer' => 'File viewer',
	'name' => 'Name',
	'last_modified' => 'Last modified',
	'modal_title' => 'Modal title',
	'unauthorized' => 'Unauthorized.',
	'your_session_has_expired_please_login_again' => 'Your session has expired. Please <a href="/login">login</a> again.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Your form was submitted. Submitting once more might cause bugs.',
	'need_help' => 'Need help?<br />Or custom solution?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Your custom controller!',

	'custom_controller_index' => 'Custom controller index.',
	'create' => 'Create',
	'view' => 'View',
	'dashboard' => 'Dashboard',
	'clone_crud' => 'Clone Crud',
	'optional_selection' => 'Optional selection',
	'you_must_add_at_least_one_field_to_the_crud' => 'You must add at least one field to the CRUD',
	'edit_crud' => 'Edit Crud',
	'crud_deleted' => 'CRUD deleted',
	'they_could_not_load_your_custom_model' => 'They could not load your custom model...',
	'they_failed_to_get_table_information' => 'They failed to get table information...',
	'they_failed_to_destroy_information' => 'They failed to destroy information...',
	'they_failed_to_store_data' => 'They failed to store data...',
	'they_failed_to_store_the_data' => 'They failed to store the data...',
	'class' => 'Class',
	'does_not_exist' => 'does not exist.',
	'they_failed_to_get_relations_information' => 'They failed to get relations information...',
	'row_created' => 'Row created',
	'they_failed_to_get_required_information' => 'They failed to get required information...',
	'row_updated' => 'Row updated',
	'row_deleted' => 'Row deleted',
	'they_could_not_load_your_custom_relationship_model' => 'They could not load your custom relationship model...',
	'please_select' => 'Please select',
	'page_not_found' => 'Page not found',
	'this_item_has_child_items_attached_to_it' => 'This item has child items attached to it',
	'they_failed_to_proceed_with_your_payment' => 'They failed to proceed with your payment...',
	'request_does_not_have_a_stripetoken' => 'Request does not have a stripeToken',
	'quick_admin_panel_charge' => 'Quick Admin Panel charge',
	'they_failed_to_charge_your_card' => 'They failed to charge your card...',
	'crud_builder' => 'CRUD Builder',

	// FIELDS
	'optional' => 'Optional',
	'required' => 'Required',
	'required__unique' => 'Required & unique',

	'no' => 'No',
	'yes' => 'Yes',
	'checked' => 'Checked',
	'unchecked' => 'Unchecked',

	'text' => 'Text',
	'email' => 'Email',
	'long_text' => 'Long text',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Date picker',
	'date_and_time_picker' => 'Date and time picker',
	'relationship_deprecated' => 'Relationship (Deprecated)',
	'belongsto_relationship' => 'BelongsTo Relationship',
	'file' => 'File',
	'photo' => 'Photo',
	'password_hashed' => 'Password (hashed)',
	'money' => 'Money',
	'number' => 'Number',
	'float' => 'Float',
	'select_enum' => 'Select ENUM',
	'add_new'                 => 'Add new',
	'are_you_sure'            => 'Are you sure?',
	'delete'            => 'Delete',
	'back_to_list' => 'Back to list',
	
	'roles'        => 'Roles',
	'user_actions' => 'User actions',
	'users'        => 'Users',

	'title' => 'Title',
	'administrator_can_create_other_users' => 'Administrator (can create other users)',
	'simple_user' => 'Simple user',

	'user' => 'User',
	'action' => 'Action',
	'action_model' => 'Action model',
	'action_id' => 'Action id',
	'name' => 'Name',
	'email' => 'Email',
	'password' => 'Password',
	'role' => 'Role',
	'remember_token' => 'Remember token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Create',
		'save'                    => 'Save',
		'edit'                    => 'Edit',
		'view'                    => 'View',
		'update'                  => 'Update',
		'list'                    => 'List',
		'no_entries_in_table'     => 'No entries in table',
		'custom_controller_index' => 'Custom controller index.',
		'logout'                  => 'Logout',
		'add_new'                 => 'Add new',
		'are_you_sure'            => 'Are you sure?',
		'back_to_list'            => 'Back to list',
		'dashboard'				  => 'Dashboard',
		'delete'				  => 'Delete',
	],
];
