<?php

return [
	'page_title'          => 'Quickadmin Builder',
	'quickadmin_for'      => 'QuickAdminPanel für',
	'logout'              => 'Abmelden',
	'menu_manager'        => 'Menüverwaltung',
	'user_management'     => 'Benutzerverwaltung',
	'back_to_adminpanels' => 'Zurück zu den Adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Menüelement hinzufügen',
		'crud_menu_item' => 'CRUD Menüelement',
		'non_crud_menu_item' => 'CRUD-loses Menüelement',
		'parent_menu_item' => 'Eltern-Menüelement',
	],

	'menu' => [
		'no_items'                    => 'Keine Menüelemente gefunden.',
		'download'                    => 'Adminpanel herunterladen (:price)',
		'download_vip'                => 'Adminpanel herunterladen',
		'view_files'                  => 'Laravel-Dateien betrachten',
		'create_new_crud'             => 'CRUD-Menüelement erstellen',
		'create_new_custom'           => 'CRUD-loses Menüelement erstellen',
		'create_new_parent_menu_item' => 'Eltern-Menüelement erstellen',
		'drag_drop_info'              => 'Sie können die Position der Menüs via Drag\'n\'Drop ändern',
		'save_changes_warning'        => 'Änderungen werden bei einem Klick auf Positionen speichern übernommen.',
		'save_positions'              => 'Positionen speichern',
		'title'                       => 'Titel',
		'edit'                        => 'Bearbeiten',
		'clone'                       => 'Klonen',
		'delete'                      => 'Löschen',
		'used_as_relationship'        => 'Als Beziehung genutzt',
		'how_to_use'                  => 'Wie man das heruntgeladene Adminpanel benutzt',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Sie haben Adminpanel erfolgreich erworben. Nun können Sie sich die Dateien anschauen und so oft wie Sie wünschen herunterladen.
		</div>
		<p>1. Entpacken Sie das Archiv in einen Ordner Ihrer Wahl</p>
		<p>2. Bearbeiten Sie dort Ihre .env Datei mit den  Datenbank- und weiteren Einstellungen</p>
		<p>3. Führen Sie den Befehl "<i>composer install</i>" aus.</p>
		<p>4. Führen Sie den Befehl "<i>php artisan migrate --seed</i>" aus. Hinweis: seed ist wichtig, damit Ihr erstes Adminkonto erstellt werden kann.</p>
		
		<br />
		
		<p>Das ist alles, gehen Sie zu Ihrer Domain und melden sich an:</p>
		<p>
		E-Mail: admin@admin.com<br />
		Passwort: password
		</p>
		
		Viel Spaß mit Ihrem Adminpanel!
		',
		'close'                       => 'Schließen',

		'payment' => [
			'name'        => 'Einmalige Bezahlung',
			'description' => 'Komplettes Laravel-Projekt herunterladen (:price)',
		],

		'edit_custom'           => 'Eigenen Controller bearbeiten',
		'edit_parent_menu_item' => 'Eltern-Menüelement bearbeiten',
		'clone_custom'           => 'Eigenen Controller klonen',
		'clone_parent_menu_item' => 'Eltern-Menüelement klonen',
		'parent_menu_item' => 'Eltern-Menüelement',
		'visual_title' => 'Angezeigter Titel',
		'icon' => 'Icon',
		'link_to_icons' => 'Alle vorhandenen Icons betrachten - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD Einstellungen',
		'add_fields' => 'Felder hinzufügen',
		'fields_notice' => '<b>Hinweis:</b> Sie müssen <strong>keine</strong> <b>ID</b> und <b>Timestamps</b> Felder hinzufügen - diese werden automatisch erstellt.',
		'save_crud' => 'CRUD speichern',
		'parent_menu_item' => 'Eltern-Menüelement',
		'new_crud_title' => 'Neuer CRUD Titel',
		'new_visual_title' => 'Neuer anzuzeigender Titel',
		'crud_title' => 'CRUD Titel',
		'visual_title' => 'Angezeigter Titel',
        'crud_title_helper' => 'Bitte benutzen Sie nur Buchstaben, Zahlen und Leerzeichen.',
		'crud_title_second_helper' => 'Genutzt um Menüeinträge, Models, Controller, Datenbankmigrationen zu erstellen.
                <br/>Titelbeispiele: <b>Länder</b>, <b>Firmen</b>, <b>Bücher</b> usw.',
        'visual_title_helper' => 'Angezeigter Titel des CRUD, der im Menü angezeigt wird.',
        'cannot_change_title' => 'Der CRUD-Name kann nicht geändert werden, nur Felder.',
        'cannot_change_title' => 'You cannot change CRUD name, only fields.',
		'generate_following' => 'Wir werden folgendes erstellen:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Datenbanktabelle',
		'what_actions_to_generate' => 'Welche Aktionen sollen erstellt werden?',
		'create' => 'Erstellen',
		'edit' => 'Bearbeiten',
		'show' => 'Zeigen',
		'delete' => 'Löschen',
		'generate_api' => 'API Controller für dieses CRUD erstellen',
		'api_generated' => 'API für dieses CRUD wurde erstellt',
		'crud_icon' => 'CRUD Icon',
		'main_settings' => 'Haupteinstellungen',
		'field_type' => 'Feldtyp',
		'field_key' => 'Feldschlüssel',
        'belongs_to_relationship' => 'Schlüssel, der im Funktionsnamen genutzt wird (außer _id).',
        'belongs_to_relationship' => 'Key that will be used in as function name (exclude _id).',
		'field_label' => 'Feldname',
		'validation' => 'Validierung',
		'nullable' => 'Kann NULL sein',
		'in_list' => 'In Liste?',
		'in_create' => 'In Erstellen?',
		'in_edit' => 'In Bearbeiten?',
		'additional_settings' => 'Zusätzliche Einstellungen',
		'ck_editor' => 'CKEDITOR benutzen?',
		'size_mb' => 'Maximale Größe in MB',
		'width_px' => 'Maximale Breite in PX',
		'height_px' => 'Maximale Höhe in PX',
		'radio_values' => 'Radio Werte:<br/> Um einen Wert hinzufügen, klicken Sie den \'Neues Wert Set hinzufügen\'-Button und geben Sie die Daten ein.',
		'label' => 'Label',
		'value' => 'Wert',
		'add_new_key_value' => 'Neues Schlüssel/Wert Set hinzufügen',
		'default_value' => 'Standardwert',
		'relationship_model' => 'Beziehung model',
		'relationship_field' => 'Beziehung Feld',
		'enum_values' => 'ENUM-Werte (kommasepariert)',
		'save_changes' => 'Änderungen speichern',
		'notice_save_crud' => 'Drücken Sie CRUD speichern um Ihre bearbeiteten/erstellten Felder zu sichern.',
	],

	'buy_modal' => [
		'title' => 'Das Folgende erhalten Sie',
        'description' => 'Dies ist ein Screenshot eines Ordners, den Sie nach der Bezahlung herunterladen werden. Es handelt sich um ein komplettes Laravel-Projekt für Ihr :title, das sofort eingesetzt werden kann!',
		'buy' => 'KAUFEN UND JETZT HERUNTERLADEN (:price)',
	],

	're-order_fields' => 'Felder umsortieren',
	'field_type' => 'Feldtyp',
	'database_column' => 'Datenbankspalte',
	'visual_title' => 'Angezeigter Titel',
	'field_type_in_form' => 'Feldtyp im Formular',
    'field_name_in_form_and_database' => 'Feldname in Formular und Datenbank',
    'field_label_in_form_and_index_page' => 'Feldbezeichnung in Formular und Indexseite',
	'edit' => 'Bearbeiten',
	'remove_field_from_crud' => 'Feld aus CRUD entfernen',
	'remove' => 'Entfernen',
	'add_field' => 'Feld hinzufügen',
	'you_need_at_least_one_field' => 'Sie benötigen mindestens ein Feld',

	'mb' => 'MB',
	'(w)_px' => '(H) px',
	'(h)_px' => '(B) px',
	'save_crud' => 'CRUD speichern',
	'add_new_crud' => 'Neues CRUD hinzufügen',
	'download_full_laravel_project_999' => 'Komplettes Laravelprojekt herunterladen ($9.99)',
	'download_files' => 'Dateien herunterladen',
	'view_files_free' => 'Dateien betrachten (KOSTENLOS)',
	'cruds' => 'CRUDs',
	'title' => 'Titel',
	'created_at' => 'Erstellt am',
	'updated_at' => 'Aktualisiert am',
	'clone' => 'Klonen',
	'no_cruds_created_yet' => 'Bisher keine CRUDs erstellt.',
	'one_time_payment' => 'Einmalzahlung',
	'file_viewer' => 'Dateibetrachter',
	'name' => 'Name',
	'last_modified' => 'Zuletzt bearbeitet',
	'modal_title' => 'Modal Titel',
	'unauthorized' => 'Unbefugt.',
	'your_session_has_expired_please_login_again' => 'Ihre Session ist abgelaufen. Bitte <a href="/login">melden</a> Sie sich erneut an.',
    'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Ihr Formular wurde übermittelt. Mehrfaches Übermitteln könnte Fehler verursachen.',
	'need_help' => 'Benötigen Sie Hilfe?<br />Oder Anpassungen?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Ihr eigener Controller!',

	'custom_controller_index' => 'Eigner Controller Index.',
	'create' => 'Erstellen',
	'view' => 'Betrachten',
	'dashboard' => 'Dashboard',
	'clone_crud' => 'CRUD klonen',
	'optional_selection' => 'Optionale Auswahl',
	'you_must_add_at_least_one_field_to_the_crud' => 'Wenigstens ein Feld muss zum CRUD hinzugefügt werden',
	'edit_crud' => 'CRUD bearbeiten',
	'crud_deleted' => 'CRUD gelöscht',
	'they_could_not_load_your_custom_model' => 'Sie konnten Ihr eigenes Model nicht laden...',
	'they_failed_to_get_table_information' => 'Sie konnten die Tabelleninformationen nicht auslesen...',
	'they_failed_to_destroy_information' => 'Sie konnten die Informationen nicht zerstören...',
	'they_failed_to_store_data' => 'Sie konnten Daten nicht speichern...',
	'they_failed_to_store_the_data' => 'Sie konnten die Daten nicht speichern...',
	'class' => 'Klasse',
	'does_not_exist' => 'existiert nicht.',
	'they_failed_to_get_relations_information' => 'Sie konnten die Beziehungsinformationen nicht auslesen...',
	'row_created' => 'Zeile erstellt',
	'they_failed_to_get_required_information' => 'Sie konnten die benötigten Informationen nicht erhalten...',
	'row_updated' => 'Zeile aktualisiert',
	'row_deleted' => 'Zeile gelöscht',
	'they_could_not_load_your_custom_relationship_model' => 'Sie konnten Ihr eigenes Beziehungs-Model nicht laden...',
	'please_select' => 'Bitte wählen',
	'page_not_found' => 'Seite nicht gefunden',
	'this_item_has_child_items_attached_to_it' => 'Dieses Element hat Kind-Elemente angehangen',
	'they_failed_to_proceed_with_your_payment' => 'Sie konnten Ihre Bezahlung nicht verarbeiten...',
	'request_does_not_have_a_stripetoken' => 'Anfage hat kein stripeToken',
	'quick_admin_panel_charge' => 'Quick Admin Panel Kosten',
	'they_failed_to_charge_your_card' => 'Sie konnten Ihre Karte nicht belasten...',
	'crud_builder' => 'CRUD Builder',

	// FIELDS
	'optional' => 'Auf Wunsch',
	'required' => 'Benötigt',
	'required__unique' => 'Benötigt & einmalig',

	'no' => 'Nein',
	'yes' => 'Ja',
	'checked' => 'Ausgewählt',
	'unchecked' => 'Nicht ausgewählt',

	'text' => 'Text',
	'email' => 'Email',
	'long_text' => 'Langer Text',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Datumsauswahl',
	'date_and_time_picker' => 'Datum- und Zeitauswahl',
	'relationship_deprecated' => 'Beziehung (überholt)',
	'belongsto_relationship' => 'Gehört zu-Beziehung',
	'file' => 'Datei',
	'photo' => 'Foto',
	'password_hashed' => 'Passwort (gehashed)',
	'money' => 'Währung',
	'number' => 'Zahl',
	'float' => 'Fließkommazahl',
	'select_enum' => 'ENUM wählen',
	'add_new'                 => 'Hinzufügen',
	'are_you_sure'            => 'Sind Sie sicher?',
	'delete'            => 'Löschen',
	'back_to_list' => 'Zurück zur Liste',
	
	'roles'        => 'Rolllen',
	'user_actions' => 'Benutzeraktionen',
	'users'        => 'Benutzer',

	'title' => 'Title',
	'administrator_can_create_other_users' => 'Administrator (kann weitere Benutzer erstellen)',
	'simple_user' => 'Einfacher Benutzer',

	'user' => 'Benutzer',
	'action' => 'Aktion',
	'action_model' => 'Aktionsmodel',
	'action_id' => 'Aktionsid',
	'name' => 'Name',
	'email' => 'E-Mail',
	'password' => 'Passwort',
	'role' => 'Rolle',
	'remember_token' => 'Remember token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Erstellen',
		'save'                    => 'Speichern',
		'edit'                    => 'Bearbeiten',
		'view'                    => 'Betrachten',
		'update'                  => 'Aktualisieren',
		'list'                    => 'Listen',
		'no_entries_in_table'     => 'Keine Einträge in Tabelle',
		'custom_controller_index' => 'Custom controller index.',
		'logout'                  => 'Abmelden',
		'add_new'                 => 'Hinzufügen',
		'are_you_sure'            => 'Sind Sie sicher?',
		'back_to_list'            => 'Zurück zur Liste',
		'dashboard'				  => 'Dashboard',
		'delete'				  => 'Löschen',
	],
];
