<?php

return [
	'page_title'          => 'Quickadmin Yaratıcı',
	'quickadmin_for'      => 'QuickAdminPanel için',
	'logout'              => 'Çıkış',
	'menu_manager'        => 'Menü Yönetimi',
	'user_management'     => 'Kullanıcı Yönetimi',
	'back_to_adminpanels' => 'Yönetim Paneli\'ne geri dön',

	'sidebar' => [
		'add_menu_item' => 'Menüye eleman ekle',
		'crud_menu_item' => 'CRUD menü elemanı',
		'non_crud_menu_item' => 'CRUD-Olmayan menü elemanı',
		'parent_menu_item' => 'Üst menü elemanı',
	],

	'menu' => [
		'no_items'                    => 'Menü elemanı bulunamadı.',
		'download'                    => 'Yönetim Paneli indir (:price)',
		'download_vip'                => 'Yönetim Paneli indir',
		'view_files'                  => 'Laravel dosyalarını görüntüle',
		'create_new_crud'             => 'CRUD menü elemanı yarat',
		'create_new_custom'           => 'CRUD-Olmayan menü elemanı yarat',
		'create_new_parent_menu_item' => 'Üst Menü elemanı yarat',
		'drag_drop_info'              => 'Münü pozisyonlarını sürükle-bırak yöntemi ile değiştirebilirsiniz.',
		'save_changes_warning'        => 'Değişiklikler "Pozisyonları Kaydet"\'e tıkladığınızda kaydedilecektir.',
		'save_positions'              => 'Pozisyonları Kaydet',
		'title'                       => 'Başlık',
		'edit'                        => 'Düzenle',
		'clone'                       => 'Çoğalt',
		'delete'                      => 'Sil',
		'used_as_relationship'        => 'İlişki olarak kullanılır.',
		'how_to_use'                  => 'İndirilen Yönetim Paneli nasıl kullanılır ?',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Yönetim Paneli\'ni başarılı bir şekilde satın aldınız. Artık dosyalarını sınırsız olarak görüntüleyebilir ve indirebilirsiniz.
		</div>
		<p>1. Dosyları arşivden istediğiniz bir klasöre çıkartınız.</p>
		<p>2. .env dosyasında ki veritabanı bağlantıları ve diğer ayarları hazırlayın.</p>
		<p>3. "<i>composer install</i>" komutunu çalıştırın.</p>
		<p>4. "<i>php artisan migrate --seed</i>" komutunu çalıştırın. Dikkat: "seed" önemli çünkü sizin için ilk yönetim kullanıcısını oluşturacak.</p>
		
		<br />
		
		<p>Ve hazırsınız!, alan adınıza gidin ve oturum açın:</p>
		<p>
		Email: admin@admin.com<br />
		Şifre: password
		</p>
		
		Yönetim Paneli ile iyi eğlenceler!
		',
		'close'                       => 'Kapat',

		'payment' => [
			'name'        => 'Tek seferlik ödeme',
			'description' => 'Tam Laravel Projesi İndir (:price)',
		],

		'edit_custom'           => 'Özel denetçiyi düzenle',
		'edit_parent_menu_item' => 'Ana menü elemanını düzenle',
		'clone_custom'           => 'Özel denetçiyi çoğalt',
		'clone_parent_menu_item' => 'Ana menü elemanını çoğalt',
		'parent_menu_item' => 'Ana menü elemanı',
		'visual_title' => 'Görsel Başlık',
		'icon' => 'İkon',
		'link_to_icons' => 'Tüm mevcut ikonları görüntüle - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD Ayarları',
		'add_fields' => 'Alanları Ekle',
		'fields_notice' => '<b>Dikkat:</b> <b>ID</b> ve <b>Timestamps</b> alanlarını eklemeniz <strong>gerekmemektedir</strong> - bu alanlar otomatik olarak eklenmektedir.',
		'save_crud' => 'CRUD Kaydet',
		'parent_menu_item' => 'Ana menü elemanı',
		'new_crud_title' => 'Yeni CRUD Başlık',
		'new_visual_title' => 'Yeni Görsel Başlık',
		'crud_title' => 'CRUD Başlık',
		'visual_title' => 'Görsel Başlık',
		'crud_title_helper' => 'Sadece karakter, numara ve boşluk kullanabilirsiniz.',
		'crud_title_second_helper' => 'Menü elemanı, model, denetçi, veritabanı şablonu(database:migrations) yaratmada kullanılır.
                <br/>Başlık örnekleri: <b>Ülkeler</b>, <b>Şirketler</b>, <b>Kitaplar</b> vb.',
		'visual_title_helper' => 'CRUD\'un Menü\'de görünecek başlığı.',
		'cannot_change_title' => 'CRUD ismini değiştiremezsiniz, sadece alanlar değişebilir.',
		'generate_following' => 'Aşağıdakileri üreteceğiz:',
		'model' => 'Model',
		'controller' => 'Denetçi',
		'database_table' => 'Veritabanı tablosu',
		'what_actions_to_generate' => 'Hangi eylemler üretilecek?',
		'create' => 'Oluştur',
		'edit' => 'Düzenle',
		'show' => 'Göster',
		'delete' => 'Sil',
		'generate_api' => 'Bu CRUD için API Denetçisi üret',
		'api_generated' => 'Bu CRUD için API üretildi.',
		'crud_icon' => 'CRUD İkon',
		'main_settings' => 'Ana Ayarlar',
		'field_type' => 'Alan tipi',
		'field_key' => 'Alan anahtarı',
		'belongs_to_relationship' => 'Anahtar fonksiyon ismi (exclude_id) olarak kullanılacaktır.',
		'field_label' => 'Alan etiketi',
		'validation' => 'Doğrulama',
		'nullable' => 'Boşaltılabilir',
		'in_list' => 'Listede mi ?',
		'in_create' => 'Oluşturmada mı?',
		'in_edit' => 'Düzenlemede mi?',
		'additional_settings' => 'Ek ayarlar',
		'ck_editor' => 'CKEDITOR kullanılsın mı?',
		'size_mb' => 'Maksimum boyut MB olarak',
		'width_px' => 'Maksimum genişlik PX olarak',
		'height_px' => 'Maksimum yükseklik PX olarak',
		'radio_values' => 'Seçmeli değerler:<br/> değer eklemek için - tıklayınız \'Yeni Değer kümesi ekle\' butonuna ve veriyi giriniz.',
		'label' => 'Etiket',
		'value' => 'Değer',
		'add_new_key_value' => 'Yeni Anahtar/Değer kümesi ekle',
		'default_value' => 'Varsayılan değer',
		'relationship_model' => 'İlişki modeli',
		'relationship_field' => 'İlişki alanı',
		'enum_values' => 'ENUM değerleri (virgülle ayrılmış)',
		'save_changes' => 'Değişiklikleri Kaydet',
		'notice_save_crud' => 'Düzenlediğiniz/Oluşturduğunuz alanları kaydetmek için CRUD Kaydet\'e basınız.',
	],

	'buy_modal' => [
		'title' => 'Ne elde edeceksiniz',
		'description' => 'Ödemeden sonra indireceğiniz klasörün bir ekran görüntüsü. Bu sizin :title için tam Laravel projesi - hemen kullanım için hazır!',
		'buy' => 'ŞİMDİ SATIN AL VE İNDİR (:price)',
	],

	're-order_fields' => 'Alanları yeniden düzenle',
	'field_type' => 'Alan Tipi',
	'database_column' => 'Veritabanı sütun',
	'visual_title' => 'Görsel Başlık',
	'field_type_in_form' => 'Formdaki alan tipi',
	'field_name_in_form_and_database' => 'Form ve veritabanındaki alan adı',
	'field_label_in_form_and_index_page' => 'Form ve ana sayfadaki alan etiketi',
	'edit' => 'Düzenle',
	'remove_field_from_crud' => 'CRUD\'dan alanı kaldır',
	'remove' => 'Kaldır',
	'add_field' => 'Alan ekle',
	'you_need_at_least_one_field' => 'En az bir alana ihtiyacınız var.',

	'mb' => 'MB',
	'(w)_px' => '(en) px',
	'(h)_px' => '(boy) px',
	'save_crud' => 'CRUD Kaydet',
	'add_new_crud' => 'Yeni CRUD ekle',
	'download_full_laravel_project_999' => 'Tam Laravel Projesi İndir ($9.99)',
	'download_files' => 'Dosyaları indir',
	'view_files_free' => 'Dosyaları görüntüle (Bedava)',
	'cruds' => 'CRUDlar',
	'title' => 'Başlık',
	'created_at' => 'Oluşturma Zamanı',
	'updated_at' => 'Güncelleme Zamanı',
	'clone' => 'Çoğalt',
	'no_cruds_created_yet' => 'Henüz CRUD oluşturulmadı.',
	'one_time_payment' => 'Tek seferlik ödeme',
	'file_viewer' => 'Dosya görüntüleyici',
	'name' => 'İsim',
	'last_modified' => 'Son güncelleme',
	'modal_title' => 'Modal başlık',
	'unauthorized' => 'Yetkisiz.',
	'your_session_has_expired_please_login_again' => 'Oturumunuz sona erdi. Lütfen tekrar <a href="/login">oturum açın</a>.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Formunuz gönderildi. Bir kere daha göndermek hataya neden olabilir.',
	'need_help' => 'Yardıma mı ihtiyacınız var?<br />ya da özel çözüme?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Özel denetçiniz!',

	'custom_controller_index' => 'Özel denetçi indeksi.',
	'create' => 'Oluştur',
	'view' => 'Görünüm',
	'dashboard' => 'Kontrol Paneli',
	'clone_crud' => 'CRUD çoğalt',
	'optional_selection' => 'İsteğe bağlı seçenekler',
	'you_must_add_at_least_one_field_to_the_crud' => 'CRUD\'a en az bir alan eklemek zorundasınız',
	'edit_crud' => 'CRUD düzenle',
	'crud_deleted' => 'CRUD silindi',
	'they_could_not_load_your_custom_model' => 'Sizin özel modelinizi yükleyemediler...',
	'they_failed_to_get_table_information' => 'Tablo bilgilerini alırken başarısız oldular...',
	'they_failed_to_destroy_information' => 'Bilgileri yok ederken başarısız oldular...',
	'they_failed_to_store_data' => 'Veri saklarken başarısız oldular...',
	'they_failed_to_store_the_data' => 'Veriyi saklarken başarısız oldular...',
	'class' => 'Sınıf',
	'does_not_exist' => 'mevcut değil.',
	'they_failed_to_get_relations_information' => 'İlişki bilgilerini alırken başarısız oldular...',
	'row_created' => 'Satır oluşturuldu',
	'they_failed_to_get_required_information' => 'Gerekli bilgileri alırken başarısız oldular...',
	'row_updated' => 'Satır güncellendi',
	'row_deleted' => 'Satır silindi',
	'they_could_not_load_your_custom_relationship_model' => 'Sizin özel ilişki modelinizi yükleyemediler...',
	'please_select' => 'Lütfen seçiniz',
	'page_not_found' => 'Sayfa bulunamadı',
	'this_item_has_child_items_attached_to_it' => 'Bu eleman kendisi ile ilişkilendirilmiş alt elemanlara sahip',
	'they_failed_to_proceed_with_your_payment' => 'Ödemenizi devam ettirirken başarısız oldular...',
	'request_does_not_have_a_stripetoken' => 'İstek stripeToken\'a sahip değil.',
	'quick_admin_panel_charge' => 'Quick Admin Panel ücreti',
	'they_failed_to_charge_your_card' => 'Kredi kartı çekimi başarısız oldu...',
	'crud_builder' => 'CRUD Yaratıcı',

	// FIELDS
	'optional' => 'İsteğe bağlı',
	'required' => 'Gerekli',
	'required__unique' => 'Gerekli & eşsiz(unique)',

	'no' => 'Hayır',
	'yes' => 'Evet',
	'checked' => 'Kontrol edildi',
	'unchecked' => 'Kontrol edilmedi',

	'text' => 'Metin',
	'email' => 'Email',
	'long_text' => 'Uzun metin',
	'radio' => 'Seçmeli',
	'checkbox' => 'Onay kutusu',
	'date_picker' => 'Zaman seçici',
	'date_and_time_picker' => 'Tarih ve zaman seçici',
	'relationship_deprecated' => 'İlişki (Kullanmdan kaldırıldı)',
	'belongsto_relationship' => 'İlişki aittir (BelongsTo)',
	'file' => 'Dosya',
	'photo' => 'Fotoğraf',
	'password_hashed' => 'Şifre (hashed)',
	'money' => 'Para',
	'number' => 'Numara',
	'float' => 'Float',
	'select_enum' => 'ENUM seçiniz',
	'add_new'                 => 'Yeni ekle',
	'are_you_sure'            => 'Emin misiniz ?',
	'delete'            => 'Sil',
	'back_to_list' => 'Listeye geri dön',
	
	'roles'        => 'Roller',
	'user_actions' => 'Kullanıcı işlemleri',
	'users'        => 'Kullanıcılar',

	'title' => 'Başlık',
	'administrator_can_create_other_users' => 'Yönetici (diğer kullanıcıları oluşturabilir)',
	'simple_user' => 'Standart kullanıcı',

	'user' => 'Kullanıcı',
	'action' => 'İşlemler',
	'action_model' => 'İşlem modeli',
	'action_id' => 'İşlem id',
	'name' => 'İsim',
	'email' => 'Email',
	'password' => 'Şifre',
	'role' => 'Role',
	'remember_token' => 'Belirteç(token) hatırla',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Oluştur',
		'save'                    => 'Kaydet',
		'edit'                    => 'Düzenle',
		'view'                    => 'Görüntüle',
		'update'                  => 'Güncelle',
		'list'                    => 'Listele',
		'no_entries_in_table'     => 'Tabloda kayıt bulunamadı',
		'custom_controller_index' => 'Özel denetçi dizini.',
		'logout'                  => 'Çıkış yap',
		'add_new'                 => 'Yeni ekle',
		'are_you_sure'            => 'Emin misiniz?',
		'back_to_list'            => 'Listeye dön',
		'dashboard'				  => 'Kontrol Paneli',
		'delete'				  => 'Sil',

	],
];
