<?php

return [
	'page_title'          => 'Quickadmin builder',
	'quickadmin_for'      => 'QuickAdminPanel for',
	'logout'              => 'Αποσύνδεση',
	'menu_manager'        => 'Διαχείριση μενού',
	'user_management'     => 'Διαχείριση χρηστών',
	'back_to_adminpanels' => 'Απιστροφή στα adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Προσθήκη στοιχείου στο μενού',
		'crud_menu_item' => 'CRUD στοιχείο μενού',
		'non_crud_menu_item' => 'Non-CRUD στοιχείο μενού',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
	],

	'menu' => [
		'no_items'                    => 'Δεν βρέθηκαν στοιχεία μενού.',
		'download'                    => 'Μεταφόρτωση adminpanel (:price)',
		'download_vip'                => 'Μεταφόρτωση adminpanel',
		'view_files'                  => 'Εμφάνιση αρχείων Laravel',
		'create_new_crud'             => 'Δημιουργεία CRUD στοιχείου',
		'create_new_custom'           => 'Δημιουργία non-CRUD στοιχείου',
		'create_new_parent_menu_item' => 'Δημιουργία μητρικού στοιχείου μενού',
		'drag_drop_info'              => 'Μπορείτε να αλλάξετε τις θέσεις μενού με drag-drop',
		'save_changes_warning'        => 'Οι αλλαγές θα αποθηκευτούν όταν κάνετε κλικ στην Αποθήκευση θέσεων',
		'save_positions'              => 'Αποθήκευση θέσεων',
		'title'                       => 'Τίτλος',
		'edit'                        => 'Επεξεργασία',
		'clone'                       => 'Κλωνοποίηση',
		'delete'                      => 'Διαγραφή',
		'used_as_relationship'        => 'Χρησιμοποιείται ως δεσμός',
		'how_to_use'                  => 'Πώς να χρησιμοποιήσετε το μεταφορτωμένο admin panel',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Έχετε αγοράσει με επιτυχία το adminpanel. Τώρα μπορείτε να δείτε τα αρχεία και να τα κατεβάσετε απεριόριστες φορές.
		</div>
		<p>1. Αποσυμπιέστε το αρχείο στον φάκελο που επιθυμείτε</p>
		<p>2. Προετοιμάστε το αρχείο .env με την σύνδεση της βάσης δεδομένων και τυχόν άλλες ρυθμίσεις</p>
		<p>3. Eκτελέσετε την εντολή "<i>composer install</i>"</p>
		<p>4. Eκτελέσετε την εντολή "<i>php artisan migrate --seed</i>". Σημείωση: η εντολή see είναι σημαντική, διότι θα δημιουργήσει τον πρώτο χρήστη/διαχειριστή για εσάς.</p>
		
		<br />
		
		<p>Και αυτό είναι, πηγαίνετε στο domain σας και συνδεθείτε:</p>
		<p>
		Email: admin@admin.com<br />
		Password: password
		</p>
		
		Καλή διασκέδαση με το adminpanel σας!
		',
		'close'                       => 'Κλείσιμο',

		'payment' => [
			'name'        => 'Εφάπαξ πληρωμή',
			'description' => 'Μεταφόρτωση πλήρους Laravel Project (:price)',
		],

		'edit_custom'           => 'Επεξεργασία προσαρμοσμένου controller',
		'edit_parent_menu_item' => 'Επεξεργασία μητρικού στοιχείου μενού',
		'clone_custom'           => 'Κλωνοποίηση προσαρμοσμένου controller',
		'clone_parent_menu_item' => 'Κλωνοποίηση μητρικού στοιχείου μενού',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
		'visual_title' => 'Τίτλος',
		'icon' => 'Εικονίδιο',
		'link_to_icons' => 'Δείτε όλα τα εικονίδια - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD ρυθμίσεις',
		'add_fields' => 'Προσθήκη πεδίων',
		'fields_notice' => '<b>Σημείωση:</b> <strong>δεν απαιτείτε</strong> η προσθήκη <b>ID</b> και <b>Timestamps</b> πεδίων - προστίθενται αυτόματα.',
		'save_crud' => 'Αποθήκευση CRUD',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
		'new_crud_title' => 'Τίτλος νέου CRUD',
		'new_visual_title' => 'Νέος τίτλος',
		'crud_title' => 'Τίτλος CRUD',
		'visual_title' => 'Τίτλος',
		'crud_title_helper' => 'Μπορείτε να εισαγάγετε μόνο χαρακτήρες, αριθμούς και κενά διαστήματα.',
		'crud_title_second_helper' => 'Χρησιμοποιείτε για τη δημιουργία στοιχείων μενού, models, controllers, database migrations.
                <br/>Παράδειγμα τίτλου: <b>Countries</b>, <b>Companies</b>, <b>Books</b> κτλ.',
		'visual_title_helper' => 'Τίτλος του CRUD που θα εμφανίζετε στο μενού.',
		'cannot_change_title' => 'Δεν είναι δυνατή η αλλαγή του τίτλου CRUD, παρά μόνο των πεδίων.',
		'generate_following' => 'Θα δημιουργήσουμε τα ακόλουθα:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Database table',
		'what_actions_to_generate' => 'Ποιες ενέργειες θα δημιουργηθούν;',
		'create' => 'Δημιουργία',
		'edit' => 'Επεξεργασία',
		'show' => 'Εμφάνιση',
		'delete' => 'Διαγραφή',
		'generate_api' => 'Δημιουργία API Controller για αυτό το CRUD',
		'api_generated' => 'Δημιουργήθηκε API για αυτό το CRUD',
		'crud_icon' => 'CRUD εικονίδιο',
		'main_settings' => 'Κυρίως ρυθμίσεις',
		'field_type' => 'Τύπος πεδίου',
		'field_key' => 'Key πεδίου',
		'belongs_to_relationship' => 'Key που θα χρησιμοποιηθεί ως όνομα συνάρτησης (exclude _id).',
		'field_label' => 'Ετικέτα πεδίου',
		'validation' => 'Έλεγχος εγκυρότητας',
		'nullable' => 'Nullable',
		'in_list' => 'Στην λίστα;',
		'in_create' => 'Στην δημιουργία;',
		'in_edit' => 'Στην επεξεργασία;',
		'additional_settings' => 'Πρόσθετες ρυθμίσεις',
		'ck_editor' => 'Χρήση CKEDITOR;',
		'size_mb' => 'Μέγιστο μέγεθος σε MB',
		'width_px' => 'Μέγιστο πλάτος σε PX',
		'height_px' => 'Μέγιστο ύψος σε PX',
		'radio_values' => 'Radio values:<br/> To add a value - click \'Add new Value set\' button and enter the data.',
		'label' => 'Label',
		'value' => 'Value',
		'add_new_key_value' => 'Add new Key/Value set',
		'default_value' => 'Default value',
		'relationship_model' => 'Relationship model',
		'relationship_field' => 'Relationship field',
		'enum_values' => 'ENUM values (comma separated)',
		'save_changes' => 'Save changes',
		'notice_save_crud' => 'Press Save CRUD to save your edited/created fields.',
	],

	'buy_modal' => [
		'title' => 'Here\'s what you\'re gonna get',
		'description' => 'This is a screenshot of a folder you will download after payment. It\'s a full Laravel project for your :title - ready to use immediately!',
		'buy' => 'BUY AND DOWNLOAD NOW (:price)',
	],

	're-order_fields' => 'Re-order fields',
	'field_type' => 'Field Type',
	'database_column' => 'Database column',
	'visual_title' => 'Visual Title',
	'field_type_in_form' => 'Field type in form',
	'field_name_in_form_and_database' => 'Field name in form and database',
	'field_label_in_form_and_index_page' => 'Field label in form and index page',
	'edit' => 'Edit',
	'remove_field_from_crud' => 'Remove field from CRUD',
	'remove' => 'Remove',
	'add_field' => 'Add field',
	'you_need_at_least_one_field' => 'You need at least one field',

	'mb' => 'MB',
	'(w)_px' => '(w) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'Save CRUD',
	'add_new_crud' => 'Add new CRUD',
	'download_full_laravel_project_999' => 'Download Full Laravel Project ($9.99)',
	'download_files' => 'Download files',
	'view_files_free' => 'View Files (FREE)',
	'cruds' => 'CRUDs',
	'title' => 'Title',
	'created_at' => 'Created at',
	'updated_at' => 'Updated at',
	'clone' => 'Clone',
	'no_cruds_created_yet' => 'No CRUDs created yet.',
	'one_time_payment' => 'One time payment',
	'file_viewer' => 'File viewer',
	'name' => 'Name',
	'last_modified' => 'Last modified',
	'modal_title' => 'Modal title',
	'unauthorized' => 'Unauthorized.',
	'your_session_has_expired_please_login_again' => 'Your session has expired. Please <a href="/login">login</a> again.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Your form was submitted. Submitting once more might cause bugs.',
	'need_help' => 'Need help?<br />Or custom solution?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Your custom controller!',

	'custom_controller_index' => 'Custom controller index.',
	'create' => 'Create',
	'view' => 'View',
	'dashboard' => 'Dashboard',
	'clone_crud' => 'Clone Crud',
	'optional_selection' => 'Optional selection',
	'you_must_add_at_least_one_field_to_the_crud' => 'You must add at least one field to the CRUD',
	'edit_crud' => 'Edit Crud',
	'crud_deleted' => 'CRUD deleted',
	'they_could_not_load_your_custom_model' => 'They could not load your custom model...',
	'they_failed_to_get_table_information' => 'They failed to get table information...',
	'they_failed_to_destroy_information' => 'They failed to destroy information...',
	'they_failed_to_store_data' => 'They failed to store data...',
	'they_failed_to_store_the_data' => 'They failed to store the data...',
	'class' => 'Class',
	'does_not_exist' => 'does not exist.',
	'they_failed_to_get_relations_information' => 'They failed to get relations information...',
	'row_created' => 'Row created',
	'they_failed_to_get_required_information' => 'They failed to get required information...',
	'row_updated' => 'Row updated',
	'row_deleted' => 'Row deleted',
	'they_could_not_load_your_custom_relationship_model' => 'They could not load your custom relationship model...',
	'please_select' => 'Please select',
	'page_not_found' => 'Page not found',
	'this_item_has_child_items_attached_to_it' => 'This item has child items attached to it',
	'they_failed_to_proceed_with_your_payment' => 'They failed to proceed with your payment...',
	'request_does_not_have_a_stripetoken' => 'Request does not have a stripeToken',
	'quick_admin_panel_charge' => 'Quick Admin Panel charge',
	'they_failed_to_charge_your_card' => 'They failed to charge your card...',
	'crud_builder' => 'CRUD Builder',

	// FIELDS
	'optional' => 'Optional',
	'required' => 'Required',
	'required__unique' => 'Required & unique',

	'no' => 'No',
	'yes' => 'Yes',
	'checked' => 'Checked',
	'unchecked' => 'Unchecked',

	'text' => 'Text',
	'email' => 'Email',
	'long_text' => 'Long text',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Date picker',
	'date_and_time_picker' => 'Date and time picker',
	'relationship_deprecated' => 'Relationship (Deprecated)',
	'belongsto_relationship' => 'BelongsTo Relationship',
	'file' => 'File',
	'photo' => 'Photo',
	'password_hashed' => 'Password (hashed)',
	'money' => 'Money',
	'number' => 'Number',
	'float' => 'Float',
	'select_enum' => 'Select ENUM',
	'add_new'                 => 'Add new',
	'are_you_sure'            => 'Are you sure?',
	'delete'            => 'Delete',
	'back_to_list' => 'Back to list',
	
	'roles'        => 'Roles',
	'user_actions' => 'User actions',
	'users'        => 'Users',

	'title' => 'Title',
	'administrator_can_create_other_users' => 'Administrator (can create other users)',
	'simple_user' => 'Simple user',

	'user' => 'User',
	'action' => 'Action',
	'action_model' => 'Action model',
	'action_id' => 'Action id',
	'name' => 'Name',
	'email' => 'Email',
	'password' => 'Password',
	'role' => 'Role',
	'remember_token' => 'Remember token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Create',
		'save'                    => 'Save',
		'edit'                    => 'Edit',
		'view'                    => 'View',
		'update'                  => 'Update',
		'list'                    => 'List',
		'no_entries_in_table'     => 'No entries in table',
		'custom_controller_index' => 'Custom controller index.',
		'logout'                  => 'Logout',
		'add_new'                 => 'Add new',
		'are_you_sure'            => 'Are you sure?',
		'back_to_list'            => 'Back to list',
		'dashboard'				  => 'Dashboard',
		'delete'				  => 'Delete',
	],
];
