<?php

return [
	'page_title'          => 'Quickadmin builder',
	'quickadmin_for'      => 'QuickAdminPanel for',
	'logout'              => 'Αποσύνδεση',
	'menu_manager'        => 'Διαχείριση μενού',
	'user_management'     => 'Διαχείριση χρηστών',
	'back_to_adminpanels' => 'Απιστροφή στα adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Προσθήκη στοιχείου στο μενού',
		'crud_menu_item' => 'CRUD στοιχείο μενού',
		'non_crud_menu_item' => 'Non-CRUD στοιχείο μενού',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
	],

	'menu' => [
		'no_items'                    => 'Δεν βρέθηκαν στοιχεία μενού.',
		'download'                    => 'Μεταφόρτωση adminpanel (:price)',
		'download_vip'                => 'Μεταφόρτωση adminpanel',
		'view_files'                  => 'Εμφάνιση αρχείων Laravel',
		'create_new_crud'             => 'Δημιουργεία CRUD στοιχείου',
		'create_new_custom'           => 'Δημιουργία non-CRUD στοιχείου',
		'create_new_parent_menu_item' => 'Δημιουργία μητρικού στοιχείου μενού',
		'drag_drop_info'              => 'Μπορείτε να αλλάξετε τις θέσεις μενού με drag-drop',
		'save_changes_warning'        => 'Οι αλλαγές θα αποθηκευτούν όταν κάνετε κλικ στην Αποθήκευση θέσεων',
		'save_positions'              => 'Αποθήκευση θέσεων',
		'title'                       => 'Τίτλος',
		'edit'                        => 'Επεξεργασία',
		'clone'                       => 'Κλωνοποίηση',
		'delete'                      => 'Διαγραφή',
		'used_as_relationship'        => 'Χρησιμοποιείται ως δεσμός',
		'how_to_use'                  => 'Πώς να χρησιμοποιήσετε το μεταφορτωμένο admin panel',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Έχετε αγοράσει με επιτυχία το adminpanel. Τώρα μπορείτε να δείτε τα αρχεία και να τα κατεβάσετε απεριόριστες φορές.
		</div>
		<p>1. Αποσυμπιέστε το αρχείο στον φάκελο που επιθυμείτε</p>
		<p>2. Προετοιμάστε το αρχείο .env με την σύνδεση της βάσης δεδομένων και τυχόν άλλες ρυθμίσεις</p>
		<p>3. Eκτελέσετε την εντολή "<i>composer install</i>"</p>
		<p>4. Eκτελέσετε την εντολή "<i>php artisan migrate --seed</i>". Σημείωση: η εντολή see είναι σημαντική, διότι θα δημιουργήσει τον πρώτο χρήστη/διαχειριστή για εσάς.</p>
		
		<br />
		
		<p>Και αυτό είναι, πηγαίνετε στο domain σας και συνδεθείτε:</p>
		<p>
		Email: admin@admin.com<br />
		Password: password
		</p>
		
		Καλή διασκέδαση με το adminpanel σας!
		',
		'close'                       => 'Κλείσιμο',

		'payment' => [
			'name'        => 'Εφάπαξ πληρωμή',
			'description' => 'Μεταφόρτωση πλήρους Laravel Project (:price)',
		],

		'edit_custom'           => 'Επεξεργασία προσαρμοσμένου controller',
		'edit_parent_menu_item' => 'Επεξεργασία μητρικού στοιχείου μενού',
		'clone_custom'           => 'Κλωνοποίηση προσαρμοσμένου controller',
		'clone_parent_menu_item' => 'Κλωνοποίηση μητρικού στοιχείου μενού',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
		'visual_title' => 'Τίτλος',
		'icon' => 'Εικονίδιο',
		'link_to_icons' => 'Δείτε όλα τα εικονίδια - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD ρυθμίσεις',
		'add_fields' => 'Προσθήκη πεδίων',
		'fields_notice' => '<b>Σημείωση:</b> <strong>δεν απαιτείτε</strong> η προσθήκη <b>ID</b> και <b>Timestamps</b> πεδίων - προστίθενται αυτόματα.',
		'save_crud' => 'Αποθήκευση CRUD',
		'parent_menu_item' => 'Μητρικό στοιχείο μενού',
		'new_crud_title' => 'Τίτλος νέου CRUD',
		'new_visual_title' => 'Νέος τίτλος',
		'crud_title' => 'Τίτλος CRUD',
		'visual_title' => 'Τίτλος',
		'crud_title_helper' => 'Μπορείτε να εισαγάγετε μόνο χαρακτήρες, αριθμούς και κενά διαστήματα.',
		'crud_title_second_helper' => 'Χρησιμοποιείτε για τη δημιουργία στοιχείων μενού, models, controllers, database migrations.
                <br/>Παράδειγμα τίτλου: <b>Countries</b>, <b>Companies</b>, <b>Books</b> κτλ.',
		'visual_title_helper' => 'Τίτλος του CRUD που θα εμφανίζετε στο μενού.',
		'cannot_change_title' => 'Δεν είναι δυνατή η αλλαγή του τίτλου CRUD, παρά μόνο των πεδίων.',
		'generate_following' => 'Θα δημιουργήσουμε τα ακόλουθα:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Database table',
		'what_actions_to_generate' => 'Ποιες ενέργειες θα δημιουργηθούν;',
		'create' => 'Δημιουργία',
		'edit' => 'Επεξεργασία',
		'show' => 'Εμφάνιση',
		'delete' => 'Διαγραφή',
		'generate_api' => 'Δημιουργία API Controller για αυτό το CRUD',
		'api_generated' => 'Δημιουργήθηκε API για αυτό το CRUD',
		'crud_icon' => 'CRUD εικονίδιο',
		'main_settings' => 'Κυρίως ρυθμίσεις',
		'field_type' => 'Τύπος πεδίου',
		'field_key' => 'Key πεδίου',
		'belongs_to_relationship' => 'Key που θα χρησιμοποιηθεί ως όνομα συνάρτησης (exclude _id).',
		'field_label' => 'Ετικέτα πεδίου',
		'validation' => 'Έλεγχος εγκυρότητας',
		'nullable' => 'Nullable',
		'in_list' => 'Στην λίστα;',
		'in_create' => 'Στην δημιουργία;',
		'in_edit' => 'Στην επεξεργασία;',
		'additional_settings' => 'Πρόσθετες ρυθμίσεις',
		'ck_editor' => 'Χρήση CKEDITOR;',
		'size_mb' => 'Μέγιστο μέγεθος σε MB',
		'width_px' => 'Μέγιστο πλάτος σε PX',
		'height_px' => 'Μέγιστο ύψος σε PX',
		'radio_values' => 'Τιμές Radio: <br/> Για να προσθέσετε μια τιμή - κάντε κλικ στην επιλογή «Προσθήκη νέας τιμης» και εισάγετε τα δεδομένα.',
		'label' => 'Ετικέτα',
		'value' => 'Τιμή',
		'add_new_key_value' => 'Προσθήκη νέου κλειδιού/τιμής σετ',
		'default_value' => 'Προεπιλεγμένη τιμή',
		'relationship_model' => 'Μοντέλο σχέσης',
		'relationship_field' => 'Πεδίο σχέσης',
		'enum_values' => 'ENUM τιμές (διαχωρισμένες με κόμμα)',
		'save_changes' => 'Αποθήκευση αλλαγών',
		'notice_save_crud' => 'Πατήστε Αποθήκευση CRUD για να αποθηκεύσετε τα επεξεργασμένα/νέα πεδία σας.',
	],

	'buy_modal' => [
		'title' => 'Εδώ βλέπετε, τί θα πάρετε.',
		'description' => 'Αυτό είναι ένα screenshot από ένα φάκελο που θα κατεβάσετε μετά την πληρωμή. Είναι ένα πλήρες έργο Laravel για με τίτλο :title - έτοιμο για χρήση!',
		'buy' => 'ΑΓΟΡΑ ΚΑΙ ΛΗΨΗ ΤΩΡΑ (:price)',
	],

	're-order_fields' => 'Ανακατάταξη πεδίδων',
	'field_type' => 'Τύπος πεδίου',
	'database_column' => 'Στήλη βάσης δεδομένων',
	'visual_title' => 'Τίτλος',
	'field_type_in_form' => 'Τύπος πεδδίου στην φόρμα',
	'field_name_in_form_and_database' => 'Όνομα πεδίου στην φόρμα και στην βάση δεδομένων',
	'field_label_in_form_and_index_page' => 'Ετικέτα πεδίου στην φόρμα και στην σελίδα λίστας',
	'edit' => 'Επεξεργασία',
	'remove_field_from_crud' => 'Αφαίρεση πεδίου από το CRUD',
	'remove' => 'Αφαίρεση',
	'add_field' => 'Προσθήκη πεδίου',
	'you_need_at_least_one_field' => 'Είναι απαραίτητο τουλάχιστον ένα πεδίο',

	'mb' => 'MB',
	'(w)_px' => '(w) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'Αποθήκευση CRUD',
	'add_new_crud' => 'Προσθήκη νέου CRUD',
	'download_full_laravel_project_999' => 'Λήψη ολόκληρου του έργου Laravel ($9.99)',
	'download_files' => 'Λήψη αρχείων',
	'view_files_free' => 'Εμφάνιση αρχείων (FREE)',
	'cruds' => 'CRUDs',
	'title' => 'Τίτλος',
	'created_at' => 'Δημιουργήθηκε στις',
	'updated_at' => 'Ενημερώθηκε στις',
	'clone' => 'Κλωνοποίηση',
	'no_cruds_created_yet' => 'Δεν έχουν δημιουργηθεί ακόμα κάποια CRUDs.',
	'one_time_payment' => 'Εφάπαξ πληρωμή',
	'file_viewer' => 'Προβολή αρχείων',
	'name' => 'Όνομα',
	'last_modified' => 'Τελευταία αλλαγή',
	'modal_title' => 'Τίτλος Modal',
	'unauthorized' => 'Δεν επιτρέπεται.',
	'your_session_has_expired_please_login_again' => 'Η σύνδεσή σας έληξε. Παρακαλώ <a href="/login">συνδεθείτε</a> ξανά.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Η φόρμα σας απεστάλει. Η επανάληψη της αποστολής μπορεί να δημιουργήσει σφάλματα.',
	'need_help' => 'Χρειάζεστε βοήθεια;<br />Ή μια προσαρμοσμένη λύση;',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Ο προσαρμοσμένος σας controller!',

	'custom_controller_index' => 'index προσαρμοσμένου controller.',
	'create' => 'Δημιουργία',
	'view' => 'Εμφάνιση',
	'dashboard' => 'Dashboard',
	'clone_crud' => 'Κλωνοποίηση Crud',
	'optional_selection' => 'Προαιρετική επιλογή',
	'you_must_add_at_least_one_field_to_the_crud' => 'Είναι απαραίτητη η προσθήκη τουλάχιστον ένός πεδίο στο CRUD',
	'edit_crud' => 'Επεξεργασία Crud',
	'crud_deleted' => 'Το CRUD διεγράφη',
	'they_could_not_load_your_custom_model' => 'Δεν ήταν δυνατή η φόρτωση του προσαρμοσμένου model...',
	'they_failed_to_get_table_information' => 'Απέτυχε η λήψη πληροφοριών από την ταμπέλα...',
	'they_failed_to_destroy_information' => 'Απέτυχε η καταστροφή των πληροφοριών...',
	'they_failed_to_store_data' => 'Απέτυχε η αποθήκευση δεδομένων...',
	'they_failed_to_store_the_data' => 'Απέτυχε η αποθήκευση των δεδομένων...',
	'class' => 'Class',
	'does_not_exist' => 'δεν υπάρχει.',
	'they_failed_to_get_relations_information' => 'Απέτυχε η λήψη πληροφοριών σχέσεων...',
	'row_created' => 'Η σειρά δημιουργήθηκε',
	'they_failed_to_get_required_information' => 'Απέτυχε η λήψη απαιτούμενων πληροφοριών...',
	'row_updated' => 'Η σειρά ενημερώθηκε',
	'row_deleted' => 'Η σειρά διεγράφει',
	'they_could_not_load_your_custom_relationship_model' => 'Δεν ήταν δυνατή η φόρτωση του προσαρμοσμένου Model σχέσης...',
	'please_select' => 'Παρακαλώ επιλέξτε',
	'page_not_found' => 'Η σελίδα δεν βρέθηκε',
	'this_item_has_child_items_attached_to_it' => 'Αυτό το στοιχείο έχει θυγατρικά στοιχεία που συνδέονται με αυτό',
	'they_failed_to_proceed_with_your_payment' => 'Απέτυχαν να προχωρήσουν με την πληρωμή σας...',
	'request_does_not_have_a_stripetoken' => 'Η αίτηση δεν έχει stripeToken',
	'quick_admin_panel_charge' => 'Quick Admin Panel χρέωση',
	'they_failed_to_charge_your_card' => 'Απέτυχε η χρέωση της κάρτας σας...',
	'crud_builder' => 'CRUD Builder',

	// FIELDS
	'optional' => 'Προαιρετικά',
	'required' => 'Απαραίτητα',
	'required__unique' => 'Απαραίτητα & μοναδικά',

	'no' => 'Όχι',
	'yes' => 'Ναι',
	'checked' => 'Επιλεγμένο',
	'unchecked' => 'Μη επιλεγμένο',

	'text' => 'Text',
	'email' => 'Email',
	'long_text' => 'Long text',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Date picker',
	'date_and_time_picker' => 'Date and time picker',
	'relationship_deprecated' => 'Σχέση (Deprecated)',
	'belongsto_relationship' => 'BelongsTo σχέση',
	'file' => 'Αρχείο',
	'photo' => 'Φωτογραφία',
	'password_hashed' => 'Συνθυματικό (hashed)',
	'money' => 'Money',
	'number' => 'Number',
	'float' => 'Float',
	'select_enum' => 'Select ENUM',
	'add_new'                 => 'Προσθήκη νέου',
	'are_you_sure'            => 'Είστε σίγουρος;',
	'delete'            => 'Διαγραφή',
	'back_to_list' => 'Απιστροφή στην λίστα',
	
	'roles'        => 'Ρόλοι',
	'user_actions' => 'Ενέργειες χρηστών',
	'users'        => 'Χρήστες',

	'title' => 'Τίτλος',
	'administrator_can_create_other_users' => 'Διαχειριστής (μπορεί να δημιουργεί άλλους χρήστες)',
	'simple_user' => 'Απλός χρήστης',

	'user' => 'Χρήστης',
	'action' => 'Ενέργεια',
	'action_model' => 'Model ενεργειών',
	'action_id' => 'id ενέργειας',
	'name' => 'Όνομα',
	'email' => 'Email',
	'password' => 'Συνθυματικό',
	'role' => 'Ρόλος',
	'remember_token' => 'Token απομνημόνευσης',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Δημιουργία',
		'save'                    => 'Αποθήκευση',
		'edit'                    => 'Επεξεργασία',
		'view'                    => 'Εμφάνιση',
		'update'                  => 'Ενημέρωησ',
		'list'                    => 'Λίστα',
		'no_entries_in_table'     => 'Δεν υπάρχουν δεδομένα στην ταμπέλα',
		'custom_controller_index' => 'index προσαρμοσμένου controller.',
		'logout'                  => 'Αποσύνδεση',
		'add_new'                 => 'Προσθήκη νέου',
		'are_you_sure'            => 'Είστε σίγουροι;',
		'back_to_list'            => 'Επιστροφή στην λίστα',
		'dashboard'				  => 'Dashboard',
		'delete'				  => 'Διαγραφή',
	],
];
