<?php

return [
	'page_title'          => 'Creador de Quickadmin',
	'quickadmin_for'      => 'QuickAdminPanel para',
	'logout'              => 'Salir',
	'menu_manager'        => 'Administración del Menú',
	'user_management'     => 'Administración de usuario',
	'back_to_adminpanels' => 'Regresar a los paneles de administración',

	'sidebar' => [
		'add_menu_item' => 'Agregar elemento del menú',
		'crud_menu_item' => 'Elemento de menú CRUD',
		'non_crud_menu_item' => 'Elemento de menú No-CRUD',
		'parent_menu_item' => 'Elemento del menú superior',
	],

	'menu' => [
		'no_items'                    => 'No se encontraron elementos del menú.',
		'download'                    => 'Descargar adminpanel (:price)',
		'download_vip'                => 'Descargar adminpanel',
		'view_files'                  => 'Ver archivos de Laravel',
		'create_new_crud'             => 'Crear elemento del menú CRUD',
		'create_new_custom'           => 'Crear elemento del menú No-CRUD',
		'create_new_parent_menu_item' => 'Crear elemento del menú superior',
		'drag_drop_info'              => 'Puedes cambiar la posición del menú arrastrando y soltando',
		'save_changes_warning'        => 'Los cambios serán guardados cuando presiones "Guardar posiciones"',
		'save_positions'              => 'Guardar posiciones',
		'title'                       => 'Título',
		'edit'                        => 'Editar',
		'clone'                       => 'Duplicar',
		'delete'                      => 'Eliminar',
		'used_as_relationship'        => 'Usado como relación',
		'how_to_use'                  => 'Cómo usar el adminpanel que descargué',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Has comprado adminpanel satisfactoriamente. Ahora puedes ver y descargar los archivos de forma ilimitada.
		</div>
		<p>1. Extrae el archivo en la ubicación que desees</p>
		<p>2. Establece tu archivo .env con los valores para la conexión a la base de datos y demás ajustes</p>
		<p>3. Ejecuta el comando "<i>composer install</i>"</p>
		<p>4. Ejecuta el comando "<i>php artisan migrate --seed</i>". Nota: El parámetro "seed" es importante, porque creará el primer usuario administrador por ti.</p>

		<br />

		<p>Eso es todo, ya puedes ir a tu dominio e ingresar:</p>
		<p>
		Correo electrónico: admin@admin.com<br />
		Contraseña: password
		</p>

		¡Que te diviertas usando tu adminpanel!
		',
		'close'                       => 'Cerrar',

		'payment' => [
			'name'        => 'Un único pago',
			'description' => 'Descargar un proyecto completo de Laravel (:price)',
		],

		'edit_custom'           => 'Editar controlador personalizado',
		'edit_parent_menu_item' => 'Editar elemento del menú superior',
		'clone_custom'           => 'Duplicar controlador personalizado',
		'clone_parent_menu_item' => 'Duplicar elemento del menú superior',
		'parent_menu_item' => 'Elemento del menú superior',
		'visual_title' => 'Título visible',
		'icon' => 'Ícono',
		'link_to_icons' => 'Ver todos los íconos disponibles - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'Ajustes de CRUD',
		'add_fields' => 'Agregar Campos',
		'fields_notice' => '<b>Nota:</b> <strong>No</strong> es necesario agregar los campos <b>ID</b> ni <b>Timestamps</b> - Éstos son agregados automáticamente.',
		'save_crud' => 'Guardar CRUD',
		'parent_menu_item' => 'Elemento de menú superior',
		'new_crud_title' => 'Título del nuevo CRUD',
		'new_visual_title' => 'Nuevo título visible',
		'crud_title' => 'Título del CRUD',
		'visual_title' => 'Título visible',
		'crud_title_helper' => 'Sólo se pueden ingresar letras, números y espacios.',
		'crud_title_second_helper' => 'Se usa para crear un elemento de menú, modelos, controladores y migraciones de la base de datos.
                <br/>Ejemplos de título: <b>Países</b>, <b>Compañías</b>, <b>Libros</b> etc.',
		'visual_title_helper' => 'El título visible del CRUD es el que se mostrará en el menú.',
		'cannot_change_title' => 'No se puede cambiar el nombre del CRUD, sólo los campos.',
		'generate_following' => 'Se generará lo siguiente:',
		'model' => 'Modelo',
		'controller' => 'Controlador',
		'database_table' => 'Tabla de la base de datos',
		'what_actions_to_generate' => '¿Qué acciones generar?',
		'create' => 'Crear',
		'edit' => 'Editar',
		'show' => 'Mostrar',
		'delete' => 'Eliminar',
		'generate_api' => 'Generar controlador API para este CRUD',
		'api_generated' => 'La API fue generada para este CRUD',
		'crud_icon' => 'Ícono de CRUD',
		'main_settings' => 'Ajustes principales',
		'field_type' => 'Tipo del campo',
		'field_key' => 'Clave del campo',
		'belongs_to_relationship' => 'La clave que será usada como nombre de la función (excluyendo _id).',
		'field_label' => 'Etiqueta del campo',
		'validation' => 'Validación',
		'nullable' => 'Nulo',
		'in_list' => '¿En lista?',
		'in_create' => '¿En creación?',
		'in_edit' => '¿En edición?',
		'additional_settings' => 'Ajustes adicionales',
		'ck_editor' => 'Usar CKEDITOR?',
		'size_mb' => 'Tamaño máximo en MB',
		'width_px' => 'Ancho máximo en PX',
		'height_px' => 'Alto máximo en PX',
		'radio_values' => 'Valores tipo "radio button":<br/> Para agregar un valor - Presiona el botón \'Agregar un nuevo conjunto de valores\' e ingrese los datos.',
		'label' => 'Etiqueta',
		'value' => 'Valor',
		'add_new_key_value' => 'Agregar nuevo conjunto tipo Clave/Valor',
		'default_value' => 'Valor predeterminado',
		'relationship_model' => 'Modelo de la relación',
		'relationship_field' => 'Campo de la relación',
		'enum_values' => 'Valores del ENUM (separados por coma)',
		'save_changes' => 'Guardar cambios',
		'notice_save_crud' => 'Presione Guardar CRUD para guardar los valores creados o modificados.',
	],

	'buy_modal' => [
		'title' => 'Esto es lo que vas a obtener',
		'description' => 'Esta es una captura de la carpeta que podrás descargar después del pago. Se trata de un proyecto de Laravel completo para tu :title ¡Listo para ser usado de inmediato!',
		'buy' => 'COMPRAR Y DESCARGAR AHORA (:price)',
	],

	're-order_fields' => 'Re-organizar campos',
	'field_type' => 'Tipo del campo',
	'database_column' => 'Columna de la base de datos',
	'visual_title' => 'Título visible',
	'field_type_in_form' => 'Tipo de campo en el formulario',
	'field_name_in_form_and_database' => 'Nombre del campo en el formulario y la base de datos',
	'field_label_in_form_and_index_page' => 'Etiqueta del campo en formulario y página principal (index)',
	'edit' => 'Editar',
	'remove_field_from_crud' => 'Remover campo del CRUD',
	'remove' => 'Remover',
	'add_field' => 'Agregar campo',
	'you_need_at_least_one_field' => 'Es necesario al menos un campo',

	'mb' => 'MB',
	'(w)_px' => '(ancho) px',
	'(h)_px' => '(alto) px',
	'save_crud' => 'Guardar CRUD',
	'add_new_crud' => 'Agregar nuevo CRUD',
	'download_full_laravel_project_999' => 'Descargar proyecto en Laravel completo ($9.99)',
	'download_files' => 'Descargar archivos',
	'view_files_free' => 'Ver los archivos (sin costo)',
	'cruds' => 'CRUDs',
	'title' => 'Título',
	'created_at' => 'Fecha de creación',
	'updated_at' => 'Fecha de actualización',
	'clone' => 'Duplicar',
	'no_cruds_created_yet' => 'Aún no se han creado CRUDs.',
	'one_time_payment' => 'Pago por única vez',
	'file_viewer' => 'Visualizador de archivos',
	'name' => 'Nombre',
	'last_modified' => 'Última modificación',
	'modal_title' => 'Título de "Modal"',
	'unauthorized' => 'Sin autorización.',
	'your_session_has_expired_please_login_again' => 'Tu sesión ha caducado. Por favor <a href="/login">ingresa</a> de nuevo.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Tu formulario ha sido enviado. Enviarlo una vez más puede causar fallas.',
	'need_help' => '¿Necesita ayuda?<br />¿O una solución personalizada?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Tu controlador personalizado!',

	'custom_controller_index' => 'Index del controlador personalizado',
	'create' => 'Crear',
	'view' => 'Ver',
	'dashboard' => 'Tablero',
	'clone_crud' => 'Duplicar CRUD',
	'optional_selection' => 'Selección opcional',
	'you_must_add_at_least_one_field_to_the_crud' => 'Es necesario agregar al menos un campo para el CRUD',
	'edit_crud' => 'Editar CRUD',
	'crud_deleted' => 'CRUD eliminado',
	'they_could_not_load_your_custom_model' => 'Podrían no cargar tu modelo personalizado...',
	'they_failed_to_get_table_information' => 'Fallaron al obtener la información de la tabla...',
	'they_failed_to_destroy_information' => 'Fallaron al destruir la información...',
	'they_failed_to_store_data' => 'Fallaron al almacenar los datos...',
	'they_failed_to_store_the_data' => 'Fallaron al almacenar los datos...',
	'class' => 'Clase',
	'does_not_exist' => 'No existe.',
	'they_failed_to_get_relations_information' => 'Fallaron al obtener información de las relaciones...',
	'row_created' => 'Fila creada',
	'they_failed_to_get_required_information' => 'Fallaron al obtener la información requerida...',
	'row_updated' => 'Fila actualizada',
	'row_deleted' => 'Fila eliminada',
	'they_could_not_load_your_custom_relationship_model' => 'Podrían no cargar la relación personalizada de tu modelo...',
	'please_select' => 'Por favor selecciona',
	'page_not_found' => 'Página no encontrada',
	'this_item_has_child_items_attached_to_it' => 'Este elemento tiene elementos asociados',
	'they_failed_to_proceed_with_your_payment' => 'Fallaron al procesar tu pago...',
	'request_does_not_have_a_stripetoken' => 'La petición no tiene el token de stripe (stripeToken)',
	'quick_admin_panel_charge' => 'Carga de Quick Admin Panel',
	'they_failed_to_charge_your_card' => 'Fallaron al cobrar de tu tarjeta...',
	'crud_builder' => 'Creador de CRUD',

	// FIELDS
	'optional' => 'Opcional',
	'required' => 'Requerido',
	'required__unique' => 'Requerido & único',

	'no' => 'No',
	'yes' => 'Sí',
	'checked' => 'Desactivado',
	'unchecked' => 'Activado',

	'text' => 'Texto',
	'email' => 'Correo electrónico',
	'long_text' => 'Texto largo',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Selector de fechas (datePicker)',
	'date_and_time_picker' => 'Selector de hora y fecha',
	'relationship_deprecated' => 'Relación (Obsoleto)',
	'belongsto_relationship' => 'Relación pertenece a (BelongsTo)',
	'file' => 'Archivo',
	'photo' => 'Foto',
	'password_hashed' => 'Contraseña (cifrada)',
	'money' => 'Dinero',
	'number' => 'Número',
	'float' => 'Float',
	'select_enum' => 'Elegir ENUM',
	'add_new'                 => 'Agregar',
	'are_you_sure'            => 'Estás seguro?',
	'delete'            => 'Eliminar',
	'back_to_list' => 'Regresar a la lista',

	'roles'        => 'Roles',
	'user_actions' => 'Acciones de usuario',
	'users'        => 'Usuarios',

	'title' => 'Título',
	'administrator_can_create_other_users' => 'Administrador (puede crear otros usuarios)',
	'simple_user' => 'Usuario común',

	'user' => 'Usuario',
	'action' => 'Acción',
	'action_model' => 'Modelo de acción (Action)',
	'action_id' => 'Id de la acción',
	'name' => 'Nombre',
	'email' => 'Correo Electrónico',
	'password' => 'Contraseña',
	'role' => 'Rol',
	'remember_token' => 'Token de sesión activa',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Crear',
		'save'                    => 'Guardar',
		'edit'                    => 'Editar',
		'view'                    => 'Ver',
		'update'                  => 'Actualizar',
		'list'                    => 'Listar',
		'no_entries_in_table'     => 'Sin valores en la tabla',
		'custom_controller_index' => 'Índice del controlador personalizado (index).',
		'logout'                  => 'Salir',
		'add_new'                 => 'Agregar',
		'are_you_sure'            => 'Estás seguro?',
		'back_to_list'            => 'Regresar a la lista?',
		'dashboard'				  => 'Tablero',
		'delete'				  => 'Eliminar',
	],
];
