<?php

return [
	'page_title'          => 'Quickadmin builder',
	'quickadmin_for'      => 'QuickAdminPanel voor',
	'logout'              => 'Logout',
	'menu_manager'        => 'Menubeheer',
	'user_management'     => 'Gebruikerbeheer',
	'back_to_adminpanels' => 'Terug naar adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Menu element toevoegen',
		'crud_menu_item' => 'CRUD Menu Element',
		'non_crud_menu_item' => 'Niet-CRUD Menu Element',
		'parent_menu_item' => 'Parent Menu Element',
	],

	'menu' => [
		'no_items'                    => 'Geen menu elementen gevonden.',
		'download'                    => 'Adminpanel ophalen (:price)',
		'download_vip'                => 'Adminpanel ophalen',
		'view_files'                  => 'Laravel bestanden bekijken',
		'create_new_crud'             => 'Een CRUD menu element maken',
		'create_new_custom'           => 'Een niet-CRUD menu element maken',
		'create_new_parent_menu_item' => 'Een Parent menu element maken',
		'drag_drop_info'              => 'Je kan de volgorde van menu elementen wijzigen met drag-drop',
		'save_changes_warning'        => 'Wijzigingen worden opgeslaan na klik op Volgorde opslaan',
		'save_positions'              => 'Volgorde opslaan',
		'title'                       => 'Titel',
		'edit'                        => 'Bewerk',
		'clone'                       => 'Kloon',
		'delete'                      => 'Verwijder',
		'used_as_relationship'        => 'Als een relatie gebruikt',
		'how_to_use'                  => 'Hoe het binnengehaald adminpanel gebruiken',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Je hebt adminpanel succesvol gekocht. Nu kan je de bestanden ervan bekijken en het een onbeperkt aantal keer ophalen.
		</div>
		<p>1. Pak het archiefbestand uit en plaats de inhoud in een folder naar keuze</p>
		<p>2. Maak je .env bestand klaar met database verbinding en andere settings</p>
		<p>3. Doe "<i>composer install</i>" </p>
		<p>4. Doe "<i>php artisan migrate --seed</i>" . Noteer: seed is belangrijk, omdat het de eerste admin gebruiker voor jou zal maken.</p>
		
		<br />
		
		<p>En dat is het, ga naar je domein en log in:</p>
		<p>
		Email: admin@admin.com<br />
		Paswoord: password
		</p>
		
		Veel plezier met je adminpanel!
		',
		'close'                       => 'Sluit',

		'payment' => [
			'name'        => 'Eenmalige betaling',
			'description' => 'Volledig Laravel Project ophalen (:price)',
		],

		'edit_custom'           => 'Custom controller bewerken',
		'edit_parent_menu_item' => 'Parent menu element bewerken',
		'clone_custom'           => 'Custom controller klonen',
		'clone_parent_menu_item' => 'Parent menu element klonen',
		'parent_menu_item' => 'Parent menu element',
		'visual_title' => 'Zichtbare titel',
		'icon' => 'Pictogram',
		'link_to_icons' => 'Zie alle beschikbare pictogrammen - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'CRUD Instellingen',
		'add_fields' => 'Velden toevoegen',
		'fields_notice' => '<b>Noteer:</b> je <strong>moet geen</strong> velden <b>ID</b> en <b>Timestamps</b> maken - deze worden automatisch toegevoegd.',
		'save_crud' => 'CRUD opslaan',
		'parent_menu_item' => 'Parent menu element',
		'new_crud_title' => 'Nieuwe CRUD Titel',
		'new_visual_title' => 'Nieuwe Zichtbare Titel',
		'crud_title' => 'CRUD Titel',
		'visual_title' => 'Zichtbare titel',
		'crud_title_helper' => 'Je mag enkel letters, cijfers en spaties gebruiken.',
		'crud_title_second_helper' => 'Gebruikt om menu elementen, models, controllers en database migraties te maken.
                <br/>Voorbeelden van titels: <b>Landen</b>, <b>Bedrijven</b>, <b>Boeken</b> etc.',
		'visual_title_helper' => 'CRUD titel die in het menu getoond zal worden.',
		'cannot_change_title' => 'Je kan de CRUD naam niet wijzigen, enkel velden.',
		'generate_following' => 'We gaan het volgende genereren:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Database tabel',
		'what_actions_to_generate' => 'Welke acties genereren?',
		'create' => 'Maak',
		'edit' => 'Bewerk',
		'show' => 'Toon',
		'delete' => 'Verwijder',
		'generate_api' => 'Een API Controller voor deze CRUD genereren',
		'api_generated' => 'Er werd een API voor deze CRUD gegenereerd',
		'crud_icon' => 'CRUD Pictogram',
		'main_settings' => 'Hoofdinstellingen',
		'field_type' => 'Veldtype',
		'field_key' => 'Veldsleutel',
		'belongs_to_relationship' => 'Sleutel die in functienamen gebruikt zal worden (niet _id).',
		'field_label' => 'Veld label',
		'validation' => 'Validering',
		'nullable' => 'Kan NULL zijn',
		'in_list' => 'In lijst?',
		'in_create' => 'In toevoegen?',
		'in_edit' => 'In bewerken?',
		'additional_settings' => 'Bijkomende instellingen',
		'ck_editor' => 'Gebruik CKEDITOR?',
		'size_mb' => 'Max grootte in MB',
		'width_px' => 'Max breedte in PX',
		'height_px' => 'Max hoogte in PX',
		'radio_values' => 'Radio waarden:<br/> Om een waarde toe te voegen - klik op de  \'Nieuwe waardeset toevoegen\' knop en voer de gegevens in.',
		'label' => 'Label',
		'value' => 'Waarde',
		'add_new_key_value' => 'Een nieuwe set Sleutel/Waarde toevoegen',
		'default_value' => 'Standaard waarde',
		'relationship_model' => 'Relatiemodel',
		'relationship_field' => 'Relatieveld',
		'enum_values' => 'ENUM waarden (komma gescheiden)',
		'save_changes' => 'Wijzigingen opslaan',
		'notice_save_crud' => 'Druk CRUD Opslaan om aangemaakte/gewijzigde velden op te slaan.',
	],

	'buy_modal' => [
		'title' => 'Dit is wat je krijgt',
		'description' => 'Dit is een schermafbeelding van een map die je zal binnenhalen na je betaling. Het is een volledig Laravel project voor je :title - klaar om onmiddellijk gebruikt te worden!',
		'buy' => 'KOOP EN HAAL NU BINNEN (:price)',
	],

	're-order_fields' => 'Velden herschikken',
	'field_type' => 'Veldtype',
	'database_column' => 'Database kolom',
	'visual_title' => 'Zichtbare Titel',
	'field_type_in_form' => 'Veldtype in formulier',
	'field_name_in_form_and_database' => 'Veldnaam in formulier en database',
	'field_label_in_form_and_index_page' => 'Veldlabel in formulier en index pagina',
	'edit' => 'Bewerk',
	'remove_field_from_crud' => 'Verwijder veld van CRUD',
	'remove' => 'Verwijder',
	'add_field' => 'Voeg veld toe',
	'you_need_at_least_one_field' => 'Minstens 1 veld is nodig',

	'mb' => 'MB',
	'(w)_px' => '(w) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'CRUD Opslaan',
	'add_new_crud' => 'Een nieuwe CRUD maken',
	'download_full_laravel_project_999' => 'Volledig Laravel Project binnenhalen ($9.99)',
	'download_files' => 'Bestanden ophalen',
	'view_files_free' => 'Bestanden bekijken (GRATIS)',
	'cruds' => 'CRUDs',
	'title' => 'Titel',
	'created_at' => 'Gemaakt op',
	'updated_at' => 'Bewerkt op',
	'clone' => 'Kloon',
	'no_cruds_created_yet' => 'Nog geen CRUDs gemaakt.',
	'one_time_payment' => 'Eénmalige betaling',
	'file_viewer' => 'Bestand viewer',
	'name' => 'Naam',
	'last_modified' => 'Laatst gewijzigd',
	'modal_title' => 'Modal titel',
	'unauthorized' => 'Niet toeglaten.',
	'your_session_has_expired_please_login_again' => 'Je sessie is afgelopen. Opnieuw <a href="/login">inloggen</a>.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Je formulier werd verstuurd. Opnieuw verzenden kan problemen verioorzaken.',
	'need_help' => 'Hulp nodig?<br />Of een aangepaste oplossing?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Je custom controller!',

	'custom_controller_index' => 'Custom controller index.',
	'create' => 'Maak',
	'view' => 'Bekijk',
	'dashboard' => 'Boordtabel',
	'clone_crud' => 'Crud klonen',
	'optional_selection' => 'Optionele selectie',
	'you_must_add_at_least_one_field_to_the_crud' => 'Je moet minstens één veld aan de CRUD toevoegen',
	'edit_crud' => 'Crud bewerken',
	'crud_deleted' => 'CRUD verwijderd',
	'they_could_not_load_your_custom_model' => 'Ze konden je custom model niet laden ...',
	'they_failed_to_get_table_information' => 'Ze konden geen tabel informatie ophalen ...',
	'they_failed_to_destroy_information' => 'Ze konden de informatie niet vernietigen ...',
	'they_failed_to_store_data' => 'Ze konden gegevens niet opslaan ...',
	'they_failed_to_store_the_data' => 'Ze konden de gegevens niet opslaan...',
	'class' => 'Class',
	'does_not_exist' => 'bestaat niet.',
	'they_failed_to_get_relations_information' => 'Ze konden de gegevens niet ophalen ...',
	'row_created' => 'Rij aangemaakt',
	'they_failed_to_get_required_information' => 'Ze konden de verplichte gegevens niet ophalen...',
	'row_updated' => 'Rij bijgewerkt',
	'row_deleted' => 'Rij verwijderd',
	'they_could_not_load_your_custom_relationship_model' => 'Ze konden je custom relationship model niet ophalen ...',
	'please_select' => 'Kies aub',
	'page_not_found' => 'Pagina niet gevonden',
	'this_item_has_child_items_attached_to_it' => 'Dit element heeft gekoppelde kinder-elementen',
	'they_failed_to_proceed_with_your_payment' => 'Ze konden niet verdergaan met je betaling ...',
	'request_does_not_have_a_stripetoken' => 'Aanvraag heeft geen stripeToken',
	'quick_admin_panel_charge' => 'Quick Admin Panel charge',
	'they_failed_to_charge_your_card' => 'Ze konden je betaalkaart niet aanspreken...',
	'crud_builder' => 'CRUD Builder',

	// FIELDS
	'optional' => 'Optioneel',
	'required' => 'Verplicht',
	'required__unique' => 'Verplicht & uniek',

	'no' => 'Nee',
	'yes' => 'Ja',
	'checked' => 'Aangevinkt',
	'unchecked' => 'Niet aangevinkt',

	'text' => 'Tekst',
	'email' => 'Email',
	'long_text' => 'Lange tekst',
	'radio' => 'Radio',
	'checkbox' => 'Checkbox',
	'date_picker' => 'Datum picker',
	'date_and_time_picker' => 'Datum en tijd picker',
	'relationship_deprecated' => 'Relatie (niet meer gebruikt)',
	'belongsto_relationship' => 'BelongsTo Relatie',
	'file' => 'Bestand',
	'photo' => 'Foto',
	'password_hashed' => 'Paswoord (hashed)',
	'money' => 'Geld',
	'number' => 'Nummer',
	'float' => 'Float',
	'select_enum' => 'Kies ENUM',
	'add_new'                 => 'Toevoegen',
	'are_you_sure'            => 'Ben je zeker?',
	'delete'            => 'Verwijder',
	'back_to_list' => 'Terug naar lijst',
	
	'roles'        => 'Rollen',
	'user_actions' => 'Gebruiker acties',
	'users'        => 'Gebruikers',

	'title' => 'Titel',
	'administrator_can_create_other_users' => 'Administrator (kan andere gebruikers toevoegen)',
	'simple_user' => 'Eenvoudige gebruiker',

	'user' => 'Gebruiker',
	'action' => 'Actie',
	'action_model' => 'Actie model',
	'action_id' => 'Actie id',
	'name' => 'Naam',
	'email' => 'Email',
	'password' => 'Paswoord',
	'role' => 'Rol',
	'remember_token' => 'Herinner token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Toevoegen',
		'save'                    => 'Opslaan',
		'edit'                    => 'Bewerken',
		'view'                    => 'Bekijken',
		'update'                  => 'Bijwerken',
		'list'                    => 'Lijst',
		'no_entries_in_table'     => 'Geen inhoud gevonden',
		'custom_controller_index' => 'Custom controller index.',
		'logout'                  => 'Logout',
		'add_new'                 => 'Toevoegen',
		'are_you_sure'            => 'Ben je zeker?',
		'back_to_list'            => 'Terug naar lijst',
		'dashboard'				  => 'Boordtabel',
		'delete'				  => 'Verwijderen',
	],
];