<?php

return [
	'page_title'          => 'Pembangun Quickadmin',
	'quickadmin_for'      => 'QuickAdminPanel untuk',
	'logout'              => 'Keluar',
	'menu_manager'        => 'Manajemen Menu',
	'user_management'     => 'Manajemen User',
	'back_to_adminpanels' => 'Kembali ke adminpanels',

	'sidebar' => [
		'add_menu_item' => 'Menambah Item Menu',
		'crud_menu_item' => 'CRUD Item Menu',
		'non_crud_menu_item' => 'Non-CRUD Item Menu',
		'parent_menu_item' => 'Parent Item Menu',
	],

	'menu' => [
		'no_items'                    => 'Item menu tidak ditemukan.',
		'download'                    => 'Download adminpanel (:price)',
		'download_vip'                => 'Download adminpanel',
		'view_files'                  => 'Melihat file Laravel',
		'create_new_crud'             => 'Membuat CRUD item menu',
		'create_new_custom'           => 'Membuat non-CRUD item menu',
		'create_new_parent_menu_item' => 'Membuat Parent item menu',
		'drag_drop_info'              => 'Anda dapat mengubah posisi menu dengan drag-drop',
		'save_changes_warning'        => 'Perubahan akan disimpan pada saat Anda mengeklik Simpan posisi',
		'save_positions'              => 'Simpan posisi',
		'title'                       => 'Judul',
		'edit'                        => 'Edit',
		'clone'                       => 'Clone',
		'delete'                      => 'Hapus',
		'used_as_relationship'        => 'Digunakan sebagai relasi',
		'how_to_use'                  => 'Bagaimana men-download adminpanel',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Anda telah berhasil melakukan pembelian adminpanel. Sekarang Anda dapat melihat file dan men-donwload tak terbatas.
		</div>
		<p>1. Extract arsip and letakkan pada folder yang diinginkan</p>
		<p>2. Persiapkan .env file Anda dengan konfigurasi koneksi database serta konfigurasi lainnya</p>
		<p>3. Jalankan perintah "<i>composer install</i>" </p>
		<p>4. Jalankan perintah "<i>php artisan migrate --seed</i>". Perhatian: seed sangat penting, karena hal tersebut akan membuat user admin pertama kali buat Anda.</p>
		
		<br />
		
		<p>Selesai, pergi ke domain Anda dan login:</p>
		<p>
		Email: admin@admin.com<br />
		Password: password
		</p>
		
		Selamat bersenang-senang menggunakan adminpanel!
		',
		'close'                       => 'Tutup',

		'payment' => [
			'name'        => 'Satu kali pembayaran',
			'description' => 'Download Proyek Laravel Sepenuhnya (:price)',
		],

		'edit_custom'           => 'Mengedit controller yang sesuai kebutuhan Anda',
		'edit_parent_menu_item' => 'Mengedit Parent item menu',
		'clone_custom'           => 'Melakukan clone controller yang sesuai kebutuhan Anda',
		'clone_parent_menu_item' => 'Melakukan Clone Parent item menu',
		'parent_menu_item' => 'Parent item menu',
		'visual_title' => 'Visualisasi judul',
		'icon' => 'Icon',
		'link_to_icons' => 'Melihat semua icon tersedia - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'Setting CRUD',
		'add_fields' => 'Tambah Fields',
		'fields_notice' => '<b>Perhatian:</b> Anda <strong>tidak perlu</strong> menambahkan <b>ID</b> dan <b>Timestamps</b> fields - hal tersebut akan ditambahkan secara otomatis.',
		'save_crud' => 'Menyimpan CRUD',
		'parent_menu_item' => 'Parent item menu',
		'new_crud_title' => 'Judul CRUD baru',
		'new_visual_title' => 'Visualisasi Judul Baru',
		'crud_title' => 'Judul CRUD',
		'visual_title' => 'Visualisasi Judul',
		'crud_title_helper' => 'Anda hanya boleh melakukan input berupa karakter, angka and spasi.',
		'crud_title_second_helper' => 'Digunakan untuk membuat item menu, models, controllers, migrasi database.
                <br/>Contoh Judul: <b>Negara</b>, <b>Perusahaan</b>, <b>Buku</b> dll.',
		'visual_title_helper' => 'Visualisasi judul dari CRUD yang akan dimunculkan di menu.',
		'cannot_change_title' => 'Anda tidak dapat mengubah nama CRUD, hanya fields.',
		'generate_following' => 'Kita akan melakukan generate sebagai berikut:',
		'model' => 'Model',
		'controller' => 'Controller',
		'database_table' => 'Tabel Database',
		'what_actions_to_generate' => 'Tindakan apa yang harus dilakukan untuk men-generate?',
		'create' => 'Buat',
		'edit' => 'Edit',
		'show' => 'Tampilkan',
		'delete' => 'Hapus',
		'generate_api' => 'Lakukan generate API Controller untuk CRUD ini',
		'api_generated' => 'API telah di-generate untuk CRUD ini',
		'crud_icon' => 'Icon CRUD',
		'main_settings' => 'Konfigurasi utama',
		'field_type' => 'Tipe Field',
		'field_key' => 'Kunci Field',
		'belongs_to_relationship' => 'Kunci yang akan digunakan sebagai nama function (exclude _id).',
		'field_label' => 'Label Field',
		'validation' => 'Validasi',
		'nullable' => 'Nullable',
		'in_list' => 'Dalam daftar?',
		'in_create' => 'Dalam create?',
		'in_edit' => 'Dalam edit?',
		'additional_settings' => 'Setting tambahan',
		'ck_editor' => 'Menggunakan CKEDITOR?',
		'size_mb' => 'Ukuran maksimal dalam MB',
		'width_px' => 'Ukuran lebar maksimal dalam PX',
		'height_px' => 'Ukuran tinggi maksimal dalam PX',
		'radio_values' => 'Nilai dari Radio:<br/> Untuk menambahkan nilai - klik tombol \'Tambahkan nilai baru\' dan masukkan data.',
		'label' => 'Label',
		'value' => 'Nilai',
		'add_new_key_value' => 'Tambahakan Kunci/Nilai baru',
		'default_value' => 'Nilai default',
		'relationship_model' => 'Model relasi',
		'relationship_field' => 'Field relasi',
		'enum_values' => 'Nilai ENUM (dipisahkan koma)',
		'save_changes' => 'Simpan perubahan',
		'notice_save_crud' => 'Tekan Simpan CRUD untuk menyimpan hasil fields yang di-edit/buat.',
	],

	'buy_modal' => [
		'title' => 'Ini yang akan Anda dapatkan',
		'description' => 'Ini adalah screenshot dari folder yang akan Anda download sesudah pembayaran. Ini adalah proyek full Laravel Anda  :title - siap untuk digunakan!',
		'buy' => 'BELI DAN DOWNLOAD SEKARANG (:price)',
	],

	're-order_fields' => 'Urutkan kembali fields',
	'field_type' => 'Tipe Field',
	'database_column' => 'Kolom Database',
	'visual_title' => 'Visualisasi Judul',
	'field_type_in_form' => 'Tipe Field dalam form',
	'field_name_in_form_and_database' => 'Nama field dalam form dan database',
	'field_label_in_form_and_index_page' => 'Label field dalam form dan halaman index',
	'edit' => 'Edit',
	'remove_field_from_crud' => 'Hapus field dari CRUD',
	'remove' => 'Hapus',
	'add_field' => 'Tambahkan field',
	'you_need_at_least_one_field' => 'Anda perlu menambahkan paling tidak satu field',

	'mb' => 'MB',
	'(w)_px' => '(w) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'Simpan CRUD',
	'add_new_crud' => 'Tambahkan CRUD baru',
	'download_full_laravel_project_999' => 'Download Proyek Laravel Sepenuhnya ($9.99)',
	'download_files' => 'Download file',
	'view_files_free' => 'Lihat File (GRATIS)',
	'cruds' => 'CRUDs',
	'title' => 'Judul',
	'created_at' => 'Dibuat pada',
	'updated_at' => 'Di-update pada',
	'clone' => 'Clone',
	'no_cruds_created_yet' => 'CRUD belum ada yang dibuat',
	'one_time_payment' => 'Satu kali pembayaran',
	'file_viewer' => 'Fasilitas Melihat File',
	'name' => 'Nama',
	'last_modified' => 'Terakhir diubah',
	'modal_title' => 'Judul modal',
	'unauthorized' => 'Tidak berwenang',
	'your_session_has_expired_please_login_again' => 'Session Anda sudah berakhir. Silakan <a href="/login">login</a> kembali.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Form Anda sudah di-submit. Submit sekali lagi kemungkinan dapat menyebabkan bugs.',
	'need_help' => 'Perlu bantuan?<br />Atau solusi lainnya?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Controller yang sesuai kebutuhan Anda!',

	'custom_controller_index' => 'Index controller lainnya.',
	'create' => 'Buat',
	'view' => 'Lihat',
	'dashboard' => 'Dashboard',
	'clone_crud' => 'Clone Crud',
	'optional_selection' => 'Pilihan Opsional',
	'you_must_add_at_least_one_field_to_the_crud' => 'Anda paling tidak menambahkan satu field pada CRUD',
	'edit_crud' => 'Mengedit Crud',
	'crud_deleted' => 'CRUD dihapus',
	'they_could_not_load_your_custom_model' => 'Tidak dapat menge-load model Anda lainnya...',
	'they_failed_to_get_table_information' => 'Gagal untuk mendapatkan informasi tabel...',
	'they_failed_to_destroy_information' => 'Gagal untuk menghapus informasi...',
	'they_failed_to_store_data' => 'Gagal untuk menyimpan data...',
	'they_failed_to_store_the_data' => 'Gagal untuk menyimpan sebuah data...',
	'class' => 'Kelas',
	'does_not_exist' => 'tidak ada.',
	'they_failed_to_get_relations_information' => 'Gagal untuk mendapatkan informasi relasi...',
	'row_created' => 'Row terbentuk',
	'they_failed_to_get_required_information' => 'Gagal mendapatkan informasi yang diinginkan...',
	'row_updated' => 'Row di-update',
	'row_deleted' => 'Row dihapus',
	'they_could_not_load_your_custom_relationship_model' => 'Tidak dapat menge-load relasi model lainnya yang Anda inginkan...',
	'please_select' => 'Silakan pilih',
	'page_not_found' => 'Halaman tidak ditemukan',
	'this_item_has_child_items_attached_to_it' => 'Item ini memiliki child item yang dilekatkan pada item tersebut',
	'they_failed_to_proceed_with_your_payment' => 'Gagal diproses dengan pembayaran Anda...',
	'request_does_not_have_a_stripetoken' => 'Permintaan tidak memiliki stripeToken',
	'quick_admin_panel_charge' => 'Biaya Quick Admin Panel',
	'they_failed_to_charge_your_card' => 'Gagal untuk dibebankan pada kartu Anda...',
	'crud_builder' => 'Pembangun CRUD',

	// FIELDS
	'optional' => 'Opsional',
	'required' => 'Wajib',
	'required__unique' => 'Wajib & unik',

	'no' => 'Tidak',
	'yes' => 'Ya',
	'checked' => 'Cek',
	'unchecked' => 'Tidak diberi tanda cek',

	'text' => 'Teks',
	'email' => 'Email',
	'long_text' => 'Teks Panjang',
	'radio' => 'Radio',
	'checkbox' => 'Cekbox',
	'date_picker' => 'Pengambil tanggal',
	'date_and_time_picker' => 'Pengambil tanggal dan waktu',
	'relationship_deprecated' => 'Relasi (Tidak digunakan lagi)',
	'belongsto_relationship' => 'Relasi BelongsTo',
	'file' => 'File',
	'photo' => 'Foto',
	'password_hashed' => 'Password (di-hash)',
	'money' => 'Jumlah uang',
	'number' => 'Angka',
	'float' => 'Float',
	'select_enum' => 'Pilih ENUM',
	'add_new'                 => 'Tambahkan baru',
	'are_you_sure'            => 'Anda yakin?',
	'delete'            => 'Hapus',
	'back_to_list' => 'Kembali ke daftar',
	
	'roles'        => 'Wewenang',
	'user_actions' => 'Tindakan Pengguna',
	'users'        => 'Pengguna',

	'title' => 'Judul',
	'administrator_can_create_other_users' => 'Administrator (dapat membuat pengguna lainnya)',
	'simple_user' => 'Pengguna yang simpel',

	'user' => 'Pengguna',
	'action' => 'Tindakan',
	'action_model' => 'Model tindakan',
	'action_id' => 'id tindakan',
	'name' => 'Nama',
	'email' => 'Email',
	'password' => 'Password',
	'role' => 'Wewenang',
	'remember_token' => 'Ingat token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Buat',
		'save'                    => 'Simpan',
		'edit'                    => 'Edit',
		'view'                    => 'Lihat',
		'update'                  => 'Update',
		'list'                    => 'Daftar',
		'no_entries_in_table'     => 'Tidak ada data di tabel',
		'custom_controller_index' => 'Controller index yang sesuai kebutuhan Anda.',
		'logout'                  => 'Keluar',
		'add_new'                 => 'Tambahkan yang baru',
		'are_you_sure'            => 'Anda yakin?',
		'back_to_list'            => 'Kembali ke daftar',
		'dashboard'				  => 'Dashboard',
		'delete'				  => 'Hapus',
	],
];
