<?php

return [
	'page_title'          => 'Construtor QuickAdmin',
	'quickadmin_for'      => 'Painel QuickAdmin para',
	'logout'              => 'Sair',
	'menu_manager'        => 'Gerenciar Menu',
	'user_management'     => 'Gerenciar Usuários',
	'back_to_adminpanels' => 'Voltar para AdminPanel',

	'sidebar' => [
		'add_menu_item' => 'Novo Item de Menu',
		'crud_menu_item' => 'Item de Menu CRUD',
		'non_crud_menu_item' => 'Item de Menu não CRUD',
		'parent_menu_item' => 'Item de Menu Pai',
	],

	'menu' => [
		'no_items'                    => 'Nenhum item de menu.',
		'download'                    => 'Baixar AdminPainel (:price)',
		'download_vip'                => 'Baixar AdminPainel',
		'view_files'                  => 'Visualizar arquivos do Laravel',
		'create_new_crud'             => 'Criar item de menu CRUD',
		'create_new_custom'           => 'Criar item de menu não CRUD',
		'create_new_parent_menu_item' => 'Criar item de menu Pai',
		'drag_drop_info'              => 'Você pode alterar a posição do menu arrastando e soltando',
		'save_changes_warning'        => 'Alterações serão salvas quando clicar em Salvar posições',
		'save_positions'              => 'Salvar posições',
		'title'                       => 'Título',
		'edit'                        => 'Editar',
		'clone'                       => 'Clonar',
		'delete'                      => 'Excluir',
		'used_as_relationship'        => 'Usado com uma relação',
		'how_to_use'                  => 'Como utilizar o AdminPainel após o download',
		'how_to_use_instructions'     => '
		<div class="alert alert-success">
		    Voce finalizou sua compra do AdminPanel com sucesso. Agora você pode visualizar os arquivos e baixá-los quantas vezes quiser.
		</div>
		<p>1. Extraia o arquivo e coloque na pasta que desejar</p>
		<p>2. Prepare seu arquivo .env informando os dados de sua conexão com o bando de dados e outras configurações</p>
		<p>3. Execute o comando "<i>composer install</i>"</p>
		<p>4. Execute o comando "<i>php artisan migrate --seed</i>". Informação: a opção --seed é importante, pois criará seu primeiro usuário do grupo admin.</p>
		
		<br />
		
		<p>E é isso! Acesse seu sistema e faça login:</p>
		<p>
		Email: admin@admin.com<br />
		Senha: password
		</p>
		
		Divirta-se utiliznado seu AdminPanel!
		',
		'close'                       => 'Fechar',

		'payment' => [
			'name'        => 'Pagamento único',
			'description' => 'Baixar o Projeto Completo Laravel (:price)',
		],

		'edit_custom'           => 'Editar Controller Personalizado',
		'edit_parent_menu_item' => 'Editar item de menu Pai',
		'clone_custom'           => 'Clonar Controller Personalizado',
		'clone_parent_menu_item' => 'Clonar item de menu Pai',
		'parent_menu_item' => 'Item de menu Pai',
		'visual_title' => 'Descrição',
		'icon' => 'Ícone',
		'link_to_icons' => 'Visualizar todos os ícones disponíveis - <a href="http://fontawesome.io/icons/" target="_blank">http://fontawesome.io/icons/</a>',
	],

	'builder' => [
		'crud_settings' => 'Configurações de CRUD',
		'add_fields' => 'Novo Campo',
		'fields_notice' => '<b>Informação:</b> <strong>não</strong> é necessário adicionar os campos de <b>ID</b> e <b>Timestamps</b> - eles são adicionados automaticamente.',
		'save_crud' => 'Salvar o CRUD',
		'parent_menu_item' => 'Item de menu Pai',
		'new_crud_title' => 'Novo título de CRUD',
		'new_visual_title' => 'Nova Descrição',
		'crud_title' => 'Título CRUD',
		'visual_title' => 'Descrição',
		'crud_title_helper' => 'Voce deve inserir somente letras, números e espaços.',
		'crud_title_second_helper' => 'Usado para criar item de menu, modelos, controllers, migrações de banco de dados.
                <br/>Exemplos de títulos: <b>Países</b>, <b>Empresas</b>, <b>Livros</b> etc.',
		'visual_title_helper' => 'Descrição do CRUD que será mostrado no Menu.',
		'cannot_change_title' => 'O nome do CRUD não pode ser alterado, somente os campos.',
		'generate_following' => 'Vamos gerar o seguinte:',
		'model' => 'Modelo',
		'controller' => 'Controller',
		'database_table' => 'Tabela do banco de dados',
		'what_actions_to_generate' => 'Quais ações a gerar?',
		'create' => 'Criar',
		'edit' => 'Editar',
		'show' => 'Mostrar',
		'delete' => 'Excluir',
		'generate_api' => 'Gerar API para este CRUD',
		'api_generated' => 'API foi gerada para este CRUD',
		'crud_icon' => 'Ícone do CRUD',
		'main_settings' => 'Configurações principais',
		'field_type' => 'Tipo do Campo',
		'field_key' => 'Nome do Campo',
		'belongs_to_relationship' => 'Texto que será usado como nome da função (excluir o _id).',
		'field_label' => 'Descrição do Campo',
		'validation' => 'Validação',
		'nullable' => 'Pode ser vazio?',
		'in_list' => 'Na listagem?',
		'in_create' => 'Na criação?',
		'in_edit' => 'Na edição?',
		'additional_settings' => 'Configurações adicionais',
		'ck_editor' => 'Usar CKEDITOR?',
		'size_mb' => 'Tamanho máximo em MB',
		'width_px' => 'Largura máxima em PX',
		'height_px' => 'Altura máxima em PX',
		'radio_values' => 'Valores da lista:<br/> Para adicionar um valor - clique no botão \'Novo item Chave/Valor\' e insira a informação.',
		'label' => 'Descrição',
		'value' => 'Valor',
		'add_new_key_value' => 'Novo item Chave/Valor',
		'default_value' => 'Valor padrão',
		'relationship_model' => 'Modelo para relacionamento',
		'relationship_field' => 'Campo de relacionamento',
		'enum_values' => 'ENUM valures (separados por vírgula)',
		'save_changes' => 'Salvar alterações',
		'notice_save_crud' => 'Pressione Salvar CRUD para salvar a edição/criação do seu campo.',
	],

	'buy_modal' => [
		'title' => 'Isto é o que você terá!',
		'description' => 'Este é o exemplo de uma pasta que baixar após o pagamento. É um projeto completo desenvolvido em Laravel para o seu :title - pronto para uso imediato!',
		'buy' => 'COMPRE E BAIXE AGORA (:price)',
	],

	're-order_fields' => 'Reordenar campos',
	'field_type' => 'Tipo do Campo',
	'database_column' => 'Colunda da tabela',
	'visual_title' => 'Descrição',
	'field_type_in_form' => 'Tipo de campo no formulário',
	'field_name_in_form_and_database' => 'Nome do campo no formulário e na tabela',
	'field_label_in_form_and_index_page' => 'Nome do campo no formulário e no índice',
	'edit' => 'Editar',
	'remove_field_from_crud' => 'Excluir campo do CRUD',
	'remove' => 'Excluir',
	'add_field' => 'Novo campo',
	'you_need_at_least_one_field' => 'Você precisa de pelo menos um campo',

	'mb' => 'MB',
	'(w)_px' => '(L) px',
	'(h)_px' => '(h) px',
	'save_crud' => 'Salar CRUD',
	'add_new_crud' => 'Novo CRUD',
	'download_full_laravel_project_999' => 'Baixar o Projeto Completo Laravel ($9.99)',
	'download_files' => 'Baixar arquivos',
	'view_files_free' => 'Visualizar Arquivos (GRÁTIS)',
	'cruds' => 'CRUDs',
	'title' => 'Título',
	'created_at' => 'Criado em',
	'updated_at' => 'Atualizado em',
	'clone' => 'Clonar',
	'no_cruds_created_yet' => 'Nenhum CRUD criado ainda.',
	'one_time_payment' => 'Pagamento único',
	'file_viewer' => 'Visualizador de arquivo',
	'name' => 'Nome',
	'last_modified' => 'Última modificação',
	'modal_title' => 'Título Modal',
	'unauthorized' => 'Não autorizado.',
	'your_session_has_expired_please_login_again' => 'Sua sessão expirou. Favor efetuar o <a href="/login">login</a> novamente.',
	'your_form_was_submitted_submitting_once_more_might_cause_bugs' => 'Seu formulário foi enviado. Enviar novamente pode causar erros.',
	'need_help' => 'Precisa de ajuda?<br />Ou solução personalizada?',
	'infolaraveldailycom' => 'info@laraveldaily.com',
	'your_custom_controller' => 'Seu Controller personalizado!',

	'custom_controller_index' => 'Índice de Controller personalizado.',
	'create' => 'Criar',
	'view' => 'Visualizar',
	'dashboard' => 'Painel',
	'clone_crud' => 'Clonar Crud',
	'optional_selection' => 'Seleção opcional',
	'you_must_add_at_least_one_field_to_the_crud' => 'Você deve criar ao menos um campo para o CRUD',
	'edit_crud' => 'Editar Crud',
	'crud_deleted' => 'CRUD excluído',
	'they_could_not_load_your_custom_model' => 'Não foi possível carregar seu modelo personalizado...',
	'they_failed_to_get_table_information' => 'Houve falhas ao buscar informações da tabela...',
	'they_failed_to_destroy_information' => 'Houve falhas na exclusão de informação...',
	'they_failed_to_store_data' => 'Houve falhas na gravação dos dados...',
	'they_failed_to_store_the_data' => 'Houve falhas na gravação dos dados...',
	'class' => 'Classe',
	'does_not_exist' => 'não existe.',
	'they_failed_to_get_relations_information' => 'Houve falhas ao buscar informações de relacionamento...',
	'row_created' => 'Linha criada',
	'they_failed_to_get_required_information' => 'Houve falhas ao buscar informações...',
	'row_updated' => 'Linha atualizada',
	'row_deleted' => 'Linha excluída',
	'they_could_not_load_your_custom_relationship_model' => 'Não foi possível carregar seu modelo de relacionamento...',
	'please_select' => 'Favor selecione',
	'page_not_found' => 'Página não encontrada',
	'this_item_has_child_items_attached_to_it' => 'Este ítem possui dependentes ligados a ele',
	'they_failed_to_proceed_with_your_payment' => 'Não foi possível continuar seu pagamento...',
	'request_does_not_have_a_stripetoken' => 'Requisição não possui um Token',
	'quick_admin_panel_charge' => 'Cobrança do Quick Admin Panel',
	'they_failed_to_charge_your_card' => 'Não foi possível cobrar no seu cartão...',
	'crud_builder' => 'Construtor de CRUD',

	// FIELDS
	'optional' => 'Opcional',
	'required' => 'Obrigatório',
	'required__unique' => 'Obrigatório & único',

	'no' => 'Não',
	'yes' => 'Sim',
	'checked' => 'Marcado',
	'unchecked' => 'Desmarcado',

	'text' => 'Texto',
	'email' => 'Email',
	'long_text' => 'Text longo',
	'radio' => 'Caixa de opção',
	'checkbox' => 'Caixa de seleção',
	'date_picker' => 'Selecionador de data',
	'date_and_time_picker' => 'Selecionador de data e hora',
	'relationship_deprecated' => 'Relacionamento (Obsoleto)',
	'belongsto_relationship' => 'Pertence ao Relacionamento',
	'file' => 'Arquivo',
	'photo' => 'Foto',
	'password_hashed' => 'Senha (hashed)',
	'money' => 'Monetário',
	'number' => 'Número',
	'float' => 'Float',
	'select_enum' => 'Seleção enumerada (ENUM)',
	'add_new'                 => 'Novo',
	'are_you_sure'            => 'Tem certeza?',
	'delete'            => 'Excluir',
	'back_to_list' => 'Voltar',
	
	'roles'        => 'Grupos',
	'user_actions' => 'Ações de usuários',
	'users'        => 'Usuários',

	'title' => 'Título',
	'administrator_can_create_other_users' => 'Administrador (pode criar outros usuários)',
	'simple_user' => 'Usuário simples',

	'user' => 'Usuário',
	'action' => 'Ação',
	'action_model' => 'Modelo de ação',
	'action_id' => 'ID da ação',
	'name' => 'Nome',
	'email' => 'Email',
	'password' => 'Senha',
	'role' => 'Grupo',
	'remember_token' => 'Lembrar token',

	// Pre-defined (global) translations for generated CRUDs
	// Generator will copy 'custom_crud' elements and add them to locale file of the generated CRUD
	// Note: do not change the 'custom_crud' key name - it's used in generators to get these translations
	'custom_crud' => [
		'create'                  => 'Criar',
		'save'                    => 'Salvar',
		'edit'                    => 'Editar',
		'view'                    => 'Visualizar',
		'update'                  => 'Atualizar',
		'list'                    => 'Listar',
		'no_entries_in_table'     => 'Sem entradas na tabela',
		'custom_controller_index' => 'Índice de Controller personalizado.',
		'logout'                  => 'Sair',
		'add_new'                 => 'Novo',
		'are_you_sure'            => 'Tem certeza?',
		'back_to_list'            => 'Voltar',
		'dashboard'				  => 'Painel',
		'delete'				  => 'Excluir',
	],
];
